Repository streamlabs/desktop, pull requests merged in 2019-11, with the labels that each got.

#2255 Remove location checking from autoconfig
  app/services/auto-config/continent-map.ts
  app/services/auto-config/index.ts
Labels: ready for review

#2251 Add missing events to tipjar
  app/components/widgets/TipJar.vue.ts
  app/i18n/en-US/widgets.json
Labels: ready for review

#2256 Make forked typechecking optional
  base.config.js
  dev.config.js
Labels: ready for review

#2263 Default to audio tab when using SoundInput
  app/components/windows/MediaGallery.vue.ts
Labels: ready for review

#2219 Remove new themes badge and media share icon
  app/components/SideNav.m.less
  app/components/SideNav.tsx
  app/components/StudioFooter.vue
  app/components/StudioFooter.vue.ts
  test/media-backup.ts
Labels: ready for review

#2260 YT: close the StreamStatus window if stream has been stopped
  app/components/platforms/youtube/YoutubeStreamStatus.tsx
Labels: ready for review

#2157 translations: fail tests if translations are not found
  app/app.ts
  app/components/NavTools.tsx
  app/components/obs/inputs/ObsInput.ts
  app/components/pages/onboarding-steps/ObsImport.tsx
  app/i18n/en-US/app.json
  app/i18n/en-US/common.json
  app/i18n/en-US/facebook.json
  app/i18n/en-US/facemasks.json
  app/i18n/en-US/filters.json
  app/i18n/en-US/hotkeys.json
  app/i18n/en-US/onboarding.json
  app/i18n/en-US/performance-metric.json
  app/i18n/en-US/recent-events.json
  app/i18n/en-US/scenes.json
  app/i18n/en-US/settings.json
  app/i18n/en-US/sources.json
  app/i18n/en-US/streaming.json
  app/i18n/en-US/widget-alertbox.json
  app/i18n/en-US/widget-goal.json
  app/i18n/en-US/widget-sponsor-banner.json
  app/i18n/en-US/widget-stream-boss.json
  app/i18n/en-US/widgets.json
  app/i18n/en-US/youtube.json
  app/services/i18n/i18n.ts
  app/services/widgets/settings/chat-box.ts
  app/services/widgets/settings/stream-boss.ts
  scripts/search-untranslated.js
Labels: ready for review

#2259 Refactor startup
  app/services/app/app.ts
  app/services/core/service-initialization-observer.ts
  app/services/facemasks/index.ts
  app/services/game-overlay/index.ts
  app/services/incremental-rollout.ts
  app/services/outage-notifications.ts
  app/services/platform-apps/index.ts
  app/services/recent-events.ts
  app/services/shortcuts.ts
  app/services/streamlabels/index.ts
  app/services/user.ts
Labels: ready for review

#2282 fix game overlay redirect error
  app/services/game-overlay/index.ts
Labels: 0.19.x

#2268 Warn users before importing multiple files
  app/components/windows/Main.vue.ts
  app/i18n/en-US/common.json
  app/services/windows.ts
Labels: 0.19.x

#2275 Dejank ColorInput
  app/components/shared/inputs/ColorInput.tsx
  app/components/shared/inputs/ColorInput.vue
  app/components/shared/inputs/ColorInput.vue.ts
  app/components/shared/inputs/inputs.ts
  app/styles/inputs.less
Labels: 0.19.x, ready for review

#2279 Extra platforms Dlive and NimoTV
  app/components/pages/onboarding-steps/Connect.m.less
  app/components/pages/onboarding-steps/Connect.tsx
  app/components/pages/onboarding-steps/ExtraPlatformConnect.tsx
  app/components/shared/PlatformLogo.m.less
  app/components/shared/PlatformLogo.tsx
  app/components/shared/inputs/ListInput.vue
  app/components/shared/inputs/index.ts
  app/i18n/en-US/common.json
  app/i18n/en-US/onboarding.json
  app/i18n/en-US/settings.json
  app/services/settings/streaming/stream-settings.ts
  app/styles/buttons.less
  media/images/platforms/dlive-logo-small.png
  media/images/platforms/dlive-logo.png
  media/images/platforms/nimo-logo-small.png
  media/images/platforms/nimo-logo.png
  test/helpers/form-monkey.ts
  test/streaming.ts
Labels: 0.19.x

#2264 Fix AlertBox moderation settings
  app/components/widgets/AlertBox.vue
  app/components/widgets/AlertBox.vue.ts
Labels: 0.19.x, ready for review

#2057 Integrate hotkeys search with global search
  app/components/shared/SearchablePages.tsx
  app/components/windows/settings/Hotkeys.vue
  app/components/windows/settings/Hotkeys.vue.ts
  app/components/windows/settings/Settings.vue
  app/components/windows/settings/Settings.vue.ts
Labels: 0.19.x, ready for review

#2283 Fix chat lingering while loader is displayed
  app/components/windows/Main.vue.ts
Labels: 0.19.x

#2269 Restream v1
  app/app-services.ts
  app/components/Chat.vue.ts
  app/components/LiveDock.vue
  app/components/LiveDock.vue.ts
  app/components/StartStreamingButton.vue.ts
  app/components/pages/FacebookMerge.tsx
  app/components/pages/onboarding-steps/Connect.tsx
  app/components/shared/BrowserView.tsx
  app/components/windows/EditStreamInfo.vue
  app/components/windows/EditStreamInfo.vue.ts
  app/components/windows/Main.vue.ts
  app/components/windows/settings/StreamSettings.tsx
  app/i18n/en-US/facebook.json
  app/i18n/en-US/streaming.json
  app/services/app/app.ts
  app/services/incremental-rollout.ts
  app/services/navigation.ts
  app/services/platforms/facebook.ts
  app/services/platforms/index.ts
  app/services/platforms/mixer.ts
  app/services/platforms/twitch.ts
  app/services/platforms/twitch/tags.ts
  app/services/platforms/utils.ts
  app/services/platforms/youtube.ts
  app/services/restream.ts
  app/services/settings/streaming/stream-settings.ts
  app/services/streaming/streaming.ts
  app/services/user.ts
  base.config.js
  test/helpers/spectron/user.ts
Labels: 0.19.x

#2201 Add device configuration to onboarding
  app/app-services.ts
  app/components/MixerVolmeter.vue.ts
  app/components/pages/Onboarding.m.less
  app/components/pages/Onboarding.tsx
  app/components/pages/onboarding-steps/HardwareSetup.tsx
  app/components/shared/Display.vue.ts
  app/components/tsx-component.ts
  app/components/windows/settings/ExtraSettings.vue
  app/components/windows/settings/ExtraSettings.vue.ts
  app/i18n/en-US/onboarding.json
  app/i18n/en-US/settings.json
  app/services/hardware/default-hardware.ts
  app/services/hardware/hardware.ts
  app/services/hardware/index.ts
  app/services/onboarding.ts
  app/services/scene-collections/nodes/overlays/webcam.ts
  app/services/scene-collections/scene-collections.ts
  app/services/sources/sources.ts
  test/helpers/spectron/index.ts
  test/onboarding.ts
  test/screentest/tests/onboarding.ts
Labels: 0.19.x

#2281 Fix banner from peeking through loader
  app/components/windows/Main.vue
Labels: 0.19.x

#2280 Add untranslated strings to i18n
  app/i18n/en-US/common.json
  app/i18n/en-US/facebook.json
  app/i18n/en-US/game-overlay.json
  app/i18n/en-US/onboarding.json
  app/i18n/en-US/recent-events.json
  app/i18n/en-US/settings.json
  app/i18n/en-US/sources.json
  app/i18n/en-US/streaming.json
  app/i18n/en-US/widget-alertbox.json
  app/i18n/en-US/widget-donation-ticker.json
  app/i18n/en-US/widget-media-share.json
  app/i18n/en-US/widgets.json
  scripts/search-untranslated.js
Labels: 0.19.x

#2287 record platform in usage events
  app/services/usage-statistics.ts
Labels: 0.19.x

#2289 Add missing translation
  app/i18n/en-US/settings.json
Labels: 0.19.x

#2288 disable copy pasting text as a source
  app/services/clipboard/clipboard.ts
Labels: 0.19.x

#2290 various protected mode fixes
  app/components/StartStreamingButton.vue.ts
  app/services/platforms/twitch.ts
  app/services/settings/streaming/stream-settings.ts
  app/services/streaming/streaming.ts
  app/services/user.ts
Labels: 0.19.x

#2292 Add key to hardware config volmeter
  app/components/pages/onboarding-steps/HardwareSetup.tsx
Labels: 0.19.x

#2299 fix autoconfig
  app/services/user.ts
Labels: 0.19.x

#2293 game overlay: fix persistent settings
  app/services/game-overlay/index.ts
Labels: 0.19.x

#2298 Fix appearance settings
  app/services/customization/customization.ts
Labels: 0.19.x

#2276 Take care of some low-hanging todos
  app/app.g.less
  app/app.ts
  app/components/shared/inputs/MediaGalleryInput.vue
  app/components/shared/inputs/SoundInput.vue
  app/components/shared/inputs/TimerInput.vue.ts
  app/components/shared/inputs/TwitchTagsInput.vue
  app/components/widgets/CustomFieldsEditor.vue.ts
  app/services/announcements.ts
  app/services/customization/customization.ts
  app/services/platform-apps/api/modules/scenes.ts
  app/services/platform-apps/index.ts
Labels: ready for review

#2306 Fix colorpicker tests. (a cherry-picked commit from staging)
  test/helpers/form-monkey.ts
Labels: 0.19.x

#2304 Fix hotkeys search
  app/components/shared/SearchablePages.tsx
  app/components/windows/settings/Settings.vue
Labels: 0.19.x

#2307 Fix spacing on HelpTip icon
  app/components/shared/HelpTip.m.less
Labels: 0.19.x

#2308 game overlay: fix initialization
  app/services/game-overlay/index.ts
Labels: 0.19.x

#2309 Fix mondo color picker size
  app/components/obs/inputs/ObsColorInput.vue
  app/components/shared/inputs/ColorInput.tsx
  app/styles/inputs.less
Labels: 0.19.x, ready for review

#2310 workaround for legacy apps that modify the stream key
  app/components/StartStreamingButton.vue.ts
  app/components/pages/FacebookMerge.tsx
  app/services/platforms/facebook.ts
  app/services/platforms/mixer.ts
  app/services/platforms/twitch.ts
  app/services/platforms/youtube.ts
  app/services/settings/streaming/stream-settings.ts
Labels: 0.19.x

#2302 Fix removing images in sponsor banner
  app/components/widgets/SponsorBanner.vue.ts
Labels: ready for review

#2311 stream-settings: forbid changing stream settings when user is live
  app/components/windows/settings/StreamSettings.tsx
  app/i18n/en-US/settings.json
  test/settings/streaming.ts
  test/streaming.ts
Labels: 0.19.x

#2317 go live window: fix retrying in case of error
  app/components/windows/EditStreamInfo.vue.ts
  test/streaming.ts
Labels: 0.19.x

#2314 YT: fix viewers count
  app/services/platforms/youtube.ts
Labels: 0.19.x
