Repository streamlabs/desktop, pull requests merged in 2020-08, with the labels that each got.

#2849 Port font selectors to modern form inputs
  app/components/obs/inputs/ObsFontInput.tsx
  app/components/obs/inputs/ObsFontInput.vue
  app/components/obs/inputs/ObsGoogleFontSelector.tsx
  app/components/obs/inputs/ObsGoogleFontSelector.vue
  app/components/obs/inputs/ObsInput.ts
  app/components/obs/inputs/ObsSystemFontSelector.vue
  app/components/obs/inputs/ObsSystemFontSelector.vue.ts
  app/components/obs/inputs/index.ts
Labels: bundle release

#2859 fix game selector
  app/components/shared/inputs/TagsInput.tsx
Labels: bundle release

#2846 Port StreamlabelProperties to modern form inputs
  app/components/custom-source-properties/StreamlabelProperties.tsx
  app/components/custom-source-properties/StreamlabelProperties.vue
  app/components/windows/SourceProperties.vue.ts
  app/i18n/en-US/streamlabels.json
Labels: bundle release

#2862 Add stream title limit
  app/components/windows/go-live/CommonPlatformFields.tsx
Labels: bundle release

#2861 fix: remove the duration field from stinger transition
  app/components/TransitionSettings.vue
Labels: ready for review

#2867 Session event improvements
  app/services/game-overlay/index.ts
  app/services/scene-collections/nodes/sources.ts
  app/services/source-filters.ts
  app/services/sources/sources.ts
  app/services/transitions.ts
  app/services/usage-statistics.ts
  app/services/virtual-webcam.ts
Labels: bundle release

#2873 Fix streamlabel preview description
  app/components/custom-source-properties/StreamlabelProperties.tsx
  app/i18n/en-US/streamlabels.json
Labels: bundle release

#2868 Alertbox library
  app/app.ts
  app/components/NavTools.tsx
  app/components/SideNav.m.less
  app/components/SideNav.tsx
  app/components/pages/AlertboxLibrary.tsx
  app/components/windows/Main.vue.ts
  app/i18n/en-US/common.json
  app/i18n/en-US/widgets.json
  app/services/user/index.ts
  app/themes.g.less
Labels: bundle release

#2845 Custom RTMP destinations
  app/components/windows/go-live/DestinationSwitchers.m.less
  app/components/windows/go-live/DestinationSwitchers.tsx
  app/components/windows/go-live/GoLiveChecklist.tsx
  app/components/windows/go-live/GoLiveSettings.tsx
  app/components/windows/go-live/ScheduleStreamWindow.tsx
  app/components/windows/settings/StreamSettings.m.less
  app/components/windows/settings/StreamSettings.tsx
  app/i18n/en-US/settings.json
  app/services/restream.ts
  app/services/settings/streaming/stream-settings.ts
  app/services/streaming/streaming-api.ts
  app/services/streaming/streaming-view.ts
  app/services/streaming/streaming.ts
  test/helpers/spectron/index.ts
  test/helpers/spectron/user.ts
  test/streaming.ts
Labels: bundle release

#2866 Handle stream delay in GoLiveChecklist
  app/components/windows/go-live/GoLiveChecklist.tsx
Labels: bundle release

#2829 Get rid of services injectors in stream-view.ts
  app/components/StartStreamingButton.vue.ts
  app/components/pages/BrowseOverlays.vue.ts
  app/components/windows/go-live/GoLiveSettings.tsx
  app/components/windows/settings/StreamSettings.tsx
  app/services/core/stateful-service.ts
  app/services/restream.ts
  app/services/settings/streaming/stream-settings.ts
  app/services/streaming/streaming-view.ts
  app/services/user/index.ts
Labels: bundle release, ready for review

#2876 Duplicate items with filters
  app/services/sources/source.ts
  test/api/clipboard.ts
Labels: bundle release

#2881 remove mixer from viewercount widget properties
  app/components/widgets/ViewerCount.vue
Labels: bundle release

#2886 Fix checkboxes for Credits widget
  app/components/widgets/Credits.vue.ts
Labels: bundle release

#2884 Fix AnimationInput for fields without filters
  app/components/widgets/inputs/AnimationInput.vue.ts
Labels: bundle release

#2892 fix shouldShowToggles
  app/components/windows/go-live/DestinationSwitchers.tsx
Labels: bundle release

#2891 Fix styling on RTMP Prime CTA
  app/components/windows/settings/StreamSettings.m.less
  app/components/windows/settings/StreamSettings.tsx
Labels: bundle release

#2898 tweak notification thresholds
  app/services/troubleshooter/troubleshooter.ts
Labels: bundle release

#2904 Fix user-pool-filter
  test/helpers/spectron/user.ts
  test/startup.ts
  test/streaming.ts
Labels: bundle release

#2888 async event subscriptions
  app/services/api/internal-api-client.ts
Labels: bundle release

#2902 Fix YT redundant transition
  app/services/platforms/youtube.ts
Labels: bundle release

#2903 Close the widget window on widget delete
  app/components/widgets/WidgetSettings.vue.ts
Labels: bundle release

#2900 Fix scheduled time
  app/components/windows/go-live/ScheduleStreamWindow.tsx
Labels: bundle release

#2874 Fix screentests
  azure-pipelines.yml
  test/screentest/tests/source-props.ts
Labels: bundle release

#2899 Manually handle sentry sampling, and send to logs
  app/app.ts
  app/components/MixerVolmeter.vue.ts
  app/services/platforms/youtube.ts
  package.json
  yarn.lock
Labels: bundle release

#2908 Nav to studio when clicking prime resub link
  app/components/pages/onboarding-steps/PrimeExpiration.tsx
Labels: bundle release

#2906 enable twitter test
  test/streaming.ts
Labels: bundle release

#2883 Add Reactive Scrollbar
  .stylelintrc
  app/app.g.less
  app/components/ModalLayout.vue
  app/components/RecentEvents.m.less
  app/components/RecentEvents.tsx
  app/components/Selector.vue
  app/components/Selector.vue.ts
  app/components/Tabs.vue
  app/components/Tabs.vue.ts
  app/components/editor/elements/BaseElement.m.less
  app/components/editor/elements/BaseElement.tsx
  app/components/editor/elements/Mixer.tsx
  app/components/editor/elements/SceneSelector.vue
  app/components/editor/elements/SceneSelector.vue.ts
  app/components/editor/elements/SourceSelector.vue
  app/components/editor/elements/SourceSelector.vue.ts
  app/components/pages/LayoutEditor.m.less
  app/components/pages/LayoutEditor.tsx
  app/components/pages/Onboarding.m.less
  app/components/pages/Onboarding.tsx
  app/components/pages/PatchNotes.vue
  app/components/pages/PatchNotes.vue.ts
  app/components/shared/DropdownMenu.vue
  app/components/shared/DropdownMenu.vue.ts
  app/components/shared/HScroll.vue
  app/components/shared/HScroll.vue.ts
  app/components/shared/Scrollable.tsx
  app/components/shared/inputs/TimerInput.vue
  app/components/shared/inputs/TimerInput.vue.ts
  app/components/widgets/CodeEditor.vue
  app/components/widgets/CustomFieldsEditor.vue
  app/components/widgets/CustomFieldsEditor.vue.ts
  app/components/widgets/MedaShare.m.less
  app/components/widgets/MediaShare.tsx
  app/components/windows/AdvancedStatistics.m.less
  app/components/windows/AdvancedStatistics.tsx
  app/components/windows/MediaGallery.vue
  app/components/windows/MediaGallery.vue.ts
  app/components/windows/OverlayWindow.vue
  app/components/windows/Projector.vue
  app/components/windows/Projector.vue.ts
  app/components/windows/SceneTransitions.vue
  app/components/windows/SceneTransitions.vue.ts
  app/components/windows/SourceFilters.vue
  app/components/windows/SourceFilters.vue.ts
  app/components/windows/SourcesShowcase.vue
  app/components/windows/SourcesShowcase.vue.ts
  app/components/windows/WidgetEditor.vue
  app/components/windows/WidgetEditor.vue.ts
  app/components/windows/go-live/GoLive.m.less
  app/components/windows/go-live/GoLiveSettings.tsx
  app/components/windows/settings/Settings.vue
  app/components/windows/settings/Settings.vue.ts
  app/index.d.ts
  package.json
  yarn.lock
Labels: bundle release
