Repository streamlabs/desktop, pull requests merged in 2020-05, with the labels that each got.

#2559 60fps volmeters
  app/components/GLVolmeters.tsx
  app/components/MixerItem.vue
  app/components/MixerItem.vue.ts
  app/components/MixerVolmeter.vue.ts
  app/components/editor/elements/BaseElement.tsx
  app/components/editor/elements/Mixer.tsx
  app/components/pages/onboarding-steps/HardwareSetup.tsx
Labels: ready for review

#2490 use local scale to make autofit in auto gamecapture mode
  app/services/editor-commands/commands/modify-transform.ts
Labels: on hold

#2481 add translatable text for a placeholder
  app/i18n/en-US/sources.json
  app/services/sources/properties-managers/default-manager.ts
  shared-resources/capture-placeholder.png
Labels: on hold

#2464 use error message for outdated drivers
  app/i18n/en-US/streaming.json
  app/services/streaming/streaming.ts
Labels: on hold

#2692 Add SubscriberGoal for YouTube
  app/app-services.ts
  app/components/editor/elements/SourceSelector.vue.ts
  app/components/widgets/goal/SubscriberGoal.tsx
  app/services/sources/sources.ts
  app/services/widgets/settings/subscriber-goal.ts
  app/services/windows.ts
Labels: bundle release

#2696 prime icon in side nav
  app/components/NavTools.tsx
  app/components/SideNav.m.less
  app/i18n/en-US/common.json
Labels: bundle release

#2687 external-api: request token for local websoket clients
  app/services/api/tcp-server/tcp-server.ts
Labels: bundle release

#2698 point side nav prime to marketing
  app/components/NavTools.tsx
Labels: bundle release

#2699 Fix slider number on prime themes
  app/components/shared/inputs/SliderInput.vue
Labels: bundle release

#2694 sentry: save the API request
  app/services/api/internal-api-client.ts
  app/services/api/internal-api.ts
  app/services/api/jsonrpc/jsonrpc-api.ts
  app/services/api/jsonrpc/jsonrpc.ts
Labels: bundle release

#2702 heartbeat event
  app/services/usage-statistics.ts
Labels: bundle release
