Repository streamlabs/desktop, pull requests merged in 2020-09, with the labels that each got.

#2912 Address scrollbar bugs
  app/app.g.less
  app/components/ModalLayout.vue.ts
  app/components/Selector.vue
  app/components/pages/LayoutEditor.m.less
  app/components/pages/LayoutEditor.tsx
  app/components/shared/Scrollable.tsx
  app/components/windows/SourcesShowcase.vue
  app/components/windows/WidgetEditor.vue
  app/components/windows/go-live/GoLiveSettings.tsx
  app/components/windows/settings/Settings.vue
Labels: bundle release

#2913 add new badge to alertbox library
  app/components/SideNav.m.less
  app/components/SideNav.tsx
  app/services/navigation.ts
Labels: bundle release

#2915 Fix source properties window scroll
  app/components/ModalLayout.vue
  app/components/windows/MediaGallery.vue
  app/components/windows/WidgetEditor.vue
  app/components/windows/go-live/GoLiveWindow.tsx
  app/components/windows/settings/Settings.vue
Labels: bundle release

#2917 add app refresh API
  app/services/platform-apps/api/modules/app.ts
Labels: bundle release

#2918 Minor scroll fixes
  app/components/shared/DropdownMenu.vue
  app/components/widgets/CodeEditor.vue.ts
  app/components/widgets/MediaShare.tsx
  app/components/windows/AdvancedStatistics.tsx
  app/components/windows/PlatformAppPopOut.vue
  app/components/windows/Projector.vue
Labels: bundle release

#2919 Fix filter menu
  app/components/ModalLayout.vue
  app/components/windows/SourceFilters.vue
Labels: bundle release

#2923 Fix BrowserSourceInteraction
  app/components/windows/BrowserSourceInteraction.tsx
Labels: bundle release

#2924 Fix FFZ scroll
  app/components/windows/FFZSettings.vue
Labels: bundle release

#2921 long synchronous call warning
  app/services/api/internal-api-client.ts
Labels: bundle release, performance

#2922 performance measurement utilities
  app/util/performance.ts
Labels: bundle release, performance

#2920 vastly improved child window open time
  app/components/windows/ChildWindow.tsx
  app/services/utils.ts
  app/services/windows.ts
Labels: bundle release, performance

#2926 Fix ObsEditableListInput
  app/components/Selector.vue
  app/components/obs/inputs/ObsEditableListInput.vue
Labels: bundle release

#2935 Get rid of i18n mess in logs
  test/helpers/spectron/index.ts
Labels: bundle release

#2932 Fix screentests
  test/screentest/tests/onboarding.ts
  test/screentest/tests/streaming.ts
Labels: bundle release

#2931 Scrollbar reflow performance
  app/components/ModalLayout.vue
  app/components/Selector.vue
  app/components/Tabs.vue
  app/components/pages/LayoutEditor.tsx
  app/components/shared/DropdownMenu.vue
  app/components/shared/Scrollable.tsx
  app/components/windows/MediaGallery.vue
  app/components/windows/Projector.vue
  app/components/windows/SourceFilters.vue
  app/components/windows/SourcesShowcase.vue
  app/components/windows/WidgetEditor.vue
  app/components/windows/go-live/GoLiveSettings.tsx
  app/components/windows/settings/Settings.vue
Labels: bundle release

#2927 Fix settings window positioning
  app/components/windows/settings/Settings.vue
Labels: bundle release

#2941 fix failing tests due to log error
  app/app.ts
  test/helpers/spectron/index.ts
Labels: bundle release

#2934 Add support for prime audio in MediaGallery
  app/app.g.less
  app/components/windows/MediaGallery.vue
  app/components/windows/MediaGallery.vue.ts
  app/services/media-gallery/index.ts
  app/services/media-gallery/media-gallery.ts
  app/services/media-gallery/stock-library.ts
Labels: bundle release

#2942 Add platform icons to RecentEvents
  app/components/RecentEvents.m.less
  app/components/RecentEvents.tsx
  app/components/shared/PlatformLogo.m.less
  app/components/shared/PlatformLogo.tsx
Labels: bundle release

#2939 reduce volmeter layout thrashing
  app/components/MixerVolmeter.vue.ts
  app/services/windows.ts
Labels: bundle release, performance

#2943 alertbox library protocol links
  app/components/pages/AlertboxLibrary.tsx
  app/services/protocol-links.ts
  app/services/user/index.ts
Labels: bundle release

#2952 spectron upgrade
  package.json
  test/helpers/spectron/index.ts
  yarn.lock
Labels: bundle release

#2945 Clarify some error messages and add them to the translation system
  app/components/windows/go-live/GoLiveError.tsx
  app/i18n/en-US/streaming.json
  app/services/streaming/stream-error.ts
Labels: bundle release

#2940 Remove sync IPC from switching scenes and selecting sources
  app/components/editor/elements/SceneSelector.vue.ts
  app/components/editor/elements/SourceSelector.vue.ts
  app/services/sources/properties-managers/default-manager.ts
  app/services/sources/properties-managers/properties-manager.ts
  app/services/sources/properties-managers/streamlabels-manager.ts
  app/services/sources/properties-managers/widget-manager.ts
  app/services/sources/source.ts
  app/services/sources/sources-api.ts
  app/services/sources/sources.ts
Labels: bundle release, performance

#2916 add ffmpeg restart hotkey
  app/services/hotkeys.ts
Labels: bundle release, on hold

#2954 Disable screen tests
  azure-pipelines.yml
Labels: bundle release

#2955 fix media backup filename
  app/services/media-backup.ts
  test/media-backup.ts
Labels: bundle release

#2948 Give Copy URL option in MediaGallery less real estate
  app/components/ModalLayout.vue
  app/components/windows/ChildWindow.tsx
  app/components/windows/MediaGallery.vue
  app/components/windows/OneOffWindow.vue
Labels: bundle release

#2959 Fix facebook
  app/services/platforms/facebook.ts
  test/streaming.ts
Labels: bundle release

#2964 instantly hide the main window on shutdown
  app/services/app/app.ts
  app/services/windows.ts
Labels: bundle release

#2963 add sysinfo to session
  app/services/usage-statistics.ts
Labels: bundle release

#2965 gracefully handle unknown content in themes
  app/services/scene-collections/nodes/overlays/slots.ts
  app/services/scene-collections/parse.ts
Labels: bundle release

#2967 Disable flaky test
  test/streaming.ts
Labels: bundle release

#2970 de-transition-ify the UI
  app/app.g.less
  app/components/LiveDock.vue
  app/components/Selector.vue
  app/components/StudioFooter.vue
  app/components/editor/elements/SourceSelector.vue
  app/components/shared/CollapsibleSection.vue
  app/components/shared/CollapsibleSection.vue.ts
  app/components/shared/HelpTip.m.less
  app/components/shared/Hotkey.vue
  app/components/shared/inputs/ImagePickerInput.vue
  app/components/shared/inputs/NumberInput.vue
  app/components/shared/inputs/ToggleInput.m.less
  app/components/windows/SourcesShowcase.vue
  app/components/windows/WidgetEditor.vue
  app/components/windows/settings/Settings.vue
  app/styles/_variables.less
  app/styles/buttons.less
  app/styles/checkboxes.less
  app/styles/inputs.less
  app/styles/mixins.less
  app/styles/sl-vue-tree.less
Labels: bundle release

#2969 Dejank prime audio
  app/components/windows/MediaGallery.vue.ts
Labels: bundle release

#2971 remove synchronous IPC from main window on startup
  app/app.ts
  app/components/windows/Main.vue
  app/components/windows/Main.vue.ts
  app/services/i18n/i18n.ts
  app/services/platforms/facebook.ts
  app/services/platforms/index.ts
  app/services/platforms/mixer.ts
  app/services/platforms/twitch.ts
  app/services/platforms/youtube.ts
  app/store/index.ts
Labels: bundle release

#2986 Allow users to select their profile while importing from obs
  app/components/pages/onboarding-steps/ObsImport.m.less
  app/components/pages/onboarding-steps/ObsImport.tsx
  app/components/windows/settings/ExtraSettings.vue.ts
  app/services/onboarding.ts
Labels: bundle release

#2968 Parallel tests
  azure-pipelines.yml
  test-job-template.yml
  test/helpers/runner.js
  test/helpers/spectron/index.ts
  test/helpers/spectron/runner-utils.ts
  test/helpers/spectron/user.ts
  test/regular/streaming.ts
Labels: bundle release, ready for review

#2988 track failed userpool requests
  test/helpers/spectron/user.ts
  test/regular/streaming.ts
Labels: bundle release

#2990 make the browser element use the user partition
  app/components/editor/elements/Browser.tsx
Labels: bundle release

#2860 tests: multistream
  app/components/shared/inputs/ToggleInput.tsx
  app/components/windows/go-live/CommonPlatformFields.tsx
  app/components/windows/go-live/DestinationSwitchers.tsx
  app/components/windows/go-live/GoLiveWindow.tsx
  app/components/windows/go-live/platforms/FacebookEditStreamInfo.tsx
  app/components/windows/go-live/platforms/TwitchEditStreamInfo.tsx
  app/components/windows/go-live/platforms/youtube/YoutubeEditStreamInfo.tsx
  app/services/platforms/youtube.ts
  test/helpers/form-monkey.ts
  test/helpers/runner.js
  test/helpers/spectron/user.ts
  test/regular/streaming/multistream.ts
  test/regular/streaming/streaming.ts
Labels: bundle release, ready for review

#2991 GoLiveWindow fixes
  app/components/windows/go-live/GoLiveWindow.tsx
  app/components/windows/settings/StreamSettings.tsx
  app/services/streaming/streaming-view.ts
  app/services/streaming/streaming.ts
Labels: bundle release

#2996 Fix race condition with media backup causing flaky tests
  app/services/sources/properties-managers/default-manager.ts
  app/services/sources/source.ts
Labels: bundle release

#3001 remove locked error for now
  app/services/streaming/streaming.ts
Labels: bundle release
