Repository streamlabs/desktop, pull requests merged in 2020-10, with the labels that each got.

#3003 Track flaky tests
  test/helpers/runner.js
  test/regular/api/sources.ts
Labels: bundle release

#2994 Re-enable tests
  app/components/windows/go-live/CommonPlatformFields.tsx
  app/components/windows/settings/StreamSettings.tsx
  app/i18n/en-US/streaming.json
  test/helpers/form-monkey.ts
  test/helpers/spectron/runner-utils.ts
  test/helpers/spectron/user.ts
  test/helpers/widget-helpers.ts
  test/regular/streaming/multistream.ts
  test/regular/streaming/streaming.ts
  test/regular/widgets/goals.ts
  test/regular/widgets/stream-boss.ts
Labels: bundle release, ready for review

#3008 lazy game overlay
  app/components/windows/OneOffWindow.vue
  app/services/game-overlay/index.ts
Labels: bundle release

#3013 fix streamlabels fonts when installing themes
  app/services/sources/properties-managers/streamlabels-manager.ts
Labels: bundle release

#3009 Add prime comparison page to onboarding
  app/components/pages/Onboarding.tsx
  app/components/pages/onboarding-steps/Prime.m.less
  app/components/pages/onboarding-steps/Prime.tsx
  app/i18n/en-US/promotional-copy.json
  app/services/onboarding.ts
  app/services/user/index.ts
  test/helpers/spectron/index.ts
  test/regular/onboarding.ts
  test/screentest/tests/onboarding.ts
Labels: bundle release

#3000 Hotkeys Performance part 1
  app/components/windows/settings/HotkeyGroup.tsx
  app/components/windows/settings/Hotkeys.vue
  app/components/windows/settings/Hotkeys.vue.ts
  test/regular/settings/hotkeys.ts
Labels: bundle release, ready for review

#3015 Revert "Fix facebook"
  app/services/platforms/facebook.ts
  test/regular/streaming/streaming.ts
Labels: bundle release

#3016 save a bunch of IPC on hardware onboarding
  app/services/hardware/default-hardware.ts
Labels: bundle release

#2997 Allow to run performance tests locally
  package.json
  test/performance/performance-test-runner.js
Labels: bundle release, ready for review

#3018 Fix multistream tests
  test/regular/streaming/multistream.ts
Labels: bundle release

#3012 Add extra fields about job for analytics
  test/helpers/runner.js
Labels: bundle release

#3027 Do not save analytics for local builds
  test/helpers/runner.js
Labels: bundle release, ready for review

#3039 deinit chat on logout
  app/services/chat.ts
Labels: bundle release

#3037 fix dashboard magic link
  app/services/magic-link.ts
Labels: bundle release

#3040 fix resizing on scaled monitors
  app/services/editor.ts
Labels: bundle release

#3044 Add guard clause to base element interval
  app/components/editor/elements/BaseElement.tsx
Labels: bundle release

#3045 fix error handling for media backup
  app/services/media-backup.ts
Labels: bundle release

#3047 Change layout of prime resub page
  app/components/pages/onboarding-steps/Prime.m.less
  app/components/pages/onboarding-steps/Prime.tsx
  app/components/pages/onboarding-steps/PrimeExpiration.tsx
  app/i18n/en-US/promotional-copy.json
Labels: bundle release

#3048 Fix typing in negative numbers into NumberInput
  app/components/shared/inputs/NumberInput.vue.ts
Labels: bundle release

#3042 hide prime settings category for logged out users
  app/components/windows/settings/Settings.vue
  app/components/windows/settings/Settings.vue.ts
Labels: bundle release

#3043 move theme overlay downloads to use downloadFile helper
  app/components/pages/AlertboxLibrary.tsx
  app/components/pages/BrowseOverlays.vue.ts
  app/services/scene-collections/overlays.ts
  app/services/scene-collections/scene-collections.ts
  app/util/requests.ts
Labels: bundle release

#3049 Hotkeys take 2
  app/components/windows/settings/HotkeyGroup.tsx
  app/components/windows/settings/Hotkeys.vue
  app/components/windows/settings/Hotkeys.vue.ts
  app/components/windows/settings/Settings.vue
  test/regular/settings/hotkeys.ts
Labels: bundle release

#3050 Fix conversion in syncOffset to support negative numbers
  app/services/audio/audio.ts
Labels: bundle release

#3052 Fix conversion in syncOffset to support negative numbers
  app/services/audio/audio.ts
Labels: bundle release

#3038 Upgrade YT flow
  app/components/shared/inputs/BoolInput.tsx
  app/components/windows/go-live/GoLiveChecklist.tsx
  app/components/windows/go-live/GoLiveError.tsx
  app/components/windows/go-live/GoLiveWindow.tsx
  app/components/windows/go-live/OptimizedProfileSwitcher.tsx
  app/components/windows/go-live/PlatformSettings.tsx
  app/components/windows/go-live/platforms/youtube/YoutubeEditStreamInfo.tsx
  app/i18n/en-US/youtube.json
  app/services/platforms/base-platform.ts
  app/services/platforms/facebook.ts
  app/services/platforms/youtube.ts
  app/services/streaming/streaming-api.ts
  app/services/streaming/streaming-view.ts
  app/services/streaming/streaming.ts
  package.json
  test/helpers/form-monkey.ts
  test/regular/streaming/streaming.ts
  yarn.lock
Labels: bundle release

#3055 Fix YT settings reactivity
  app/services/platforms/base-platform.ts
Labels: bundle release

#3058 Fetch streamlabel definitions on user login
  app/components/custom-source-properties/StreamlabelProperties.tsx
  app/services/streamlabels/index.ts
Labels: bundle release

#3063 Fix closing of GoLiveWindow
  app/services/streaming/streaming.ts
Labels: bundle release

#3046 implement jfetch helper
  app/index.d.ts
  app/services/announcements.ts
  app/services/facemasks/index.ts
  app/services/font-library.ts
  app/services/incremental-rollout.ts
  app/services/integrations/twitter.ts
  app/services/magic-link.ts
  app/services/media-backup.ts
  app/services/media-gallery/media-gallery.ts
  app/services/outage-notifications.ts
  app/services/platform-apps/index.ts
  app/services/platforms/facebook.ts
  app/services/platforms/mixer.ts
  app/services/platforms/twitch.ts
  app/services/platforms/youtube.ts
  app/services/recent-events.ts
  app/services/restream.ts
  app/services/scene-collections/server-api.ts
  app/services/streamlabels/index.ts
  app/services/user/index.ts
  app/services/websocket.ts
  app/util/requests.ts
Labels: bundle release

#3066 Fix pull of YT ultra-low-latency and category
  app/components/windows/go-live/platforms/youtube/YoutubeEditStreamInfo.tsx
  app/services/platforms/youtube.ts
Labels: bundle release

#3059 fix bug when undoing deletion of a scene that exists within other scenes
  app/services/editor-commands/commands/remove-scene.ts
  app/services/scenes/scenes.ts
Labels: bundle release

#3057 Move login to settings menu
  app/components/NavTools.tsx
  app/components/windows/settings/Settings.vue
  app/components/windows/settings/Settings.vue.ts
  app/i18n/en-US/common.json
  test/helpers/spectron/user.ts
  test/regular/streaming/streaming.ts
Labels: bundle release

#3068 Add default value to metadata for color inputs
  app/components/shared/inputs/ColorInput.tsx
Labels: bundle release

#3071 enfornce the correctness of the displayOrder array
  app/services/scenes/scenes.ts
Labels: bundle release

#3080 Fix and expose Alert Parry settings
  app/components/widgets/AlertBox.vue
  app/i18n/en-US/widget-alertbox.json
  app/services/widgets/settings/alert-box/alert-box-api.ts
  app/services/widgets/settings/alert-box/index.ts
Labels: bundle release

#3069 fix sentry error when audio devices no longer exist
  app/services/settings/settings.ts
Labels: bundle release

#3067 fix error message for sentry
  app/services/streaming/streaming.ts
Labels: bundle release

#3075 set 350MB media upload limit
  app/services/media-backup.ts
Labels: bundle release

#3077 Youtube fixes
  app/components/windows/go-live/platforms/youtube/YoutubeEditStreamInfo.tsx
  app/i18n/en-US/youtube.json
  app/services/platforms/youtube.ts
  test/regular/streaming/streaming.ts
Labels: bundle release, ready for review

#3078 goLiveWindow: Suggest logout when user is trying to disable the primary platform
  app/components/shared/ModalMessageBox.m.less
  app/components/shared/ModalMessageBox.tsx
  app/components/windows/go-live/DestinationSwitchers.m.less
  app/components/windows/go-live/DestinationSwitchers.tsx
  app/i18n/en-US/streaming.json
  test/helpers/form-monkey.ts
  test/regular/streaming/streaming.ts
Labels: ready for review

#3087 fix yt low latency
  app/services/platforms/youtube.ts
Labels: bundle release
