Repository streamlabs/desktop, pull requests merged in 2021-08, with the labels that each got.

#3668 Fix floating graphic in onboarding
  app/components/windows/Main.vue
Labels: bundle release

#3669 Fix disappearing arrows in grow tab
  app/styles/antd/day-theme.lazy.less
  app/styles/antd/night-theme.lazy.less
  app/styles/antd/prime-dark.lazy.less
  app/styles/antd/prime-light.lazy.less
Labels: bundle release

#3670 Fix unit conversions in MediaShare and AlertBox
  app/services/widgets/settings/alert-box/index.ts
  app/services/widgets/settings/media-share.ts
Labels: bug, bundle release

#3667 fix volmeter vertical alignment
  app/components/GLVolmeters.tsx
Labels: bundle release

#3671 Divide ms to s in variations on fetch
  app/services/widgets/settings/alert-box/index.ts
Labels: bundle release

#3665 Add Emote Wall Widget
  app/app-services.ts
  app/components/editor/elements/SourceSelector.vue.ts
  app/components/widgets/EmoteWall.tsx
  app/i18n/en-US/widget-emote-wall.json
  app/i18n/fallback.ts
  app/services/widgets/settings/emote-wall.ts
  app/services/widgets/widgets-data.ts
  app/services/windows.ts
Labels: bundle release

#3678 Fix default size and unit conversion in emote wall
  app/services/widgets/settings/emote-wall.ts
  app/services/widgets/widgets-data.ts
Labels: bundle release

#3679 Fix nesting EmoteWall settings
  app/services/widgets/settings/emote-wall.ts
Labels: bundle release

#3675 Fix filters window name for Scenes
  app/i18n/en-US/filters.json
  app/services/source-filters.ts
Labels: bug, bundle release

#3674 Fix long names wrapping in ListInput options with images
  app/styles/antd/antd.less
Labels: bundle release

#3681 Bulletproof chat resize
  app/components/windows/Main.vue.ts
Labels: bug, bundle release

#3676 Port AppsNav to React
  app/app-services.ts
  app/components-react/index.ts
  app/components-react/sidebar/AppsNav.m.less
  app/components-react/sidebar/AppsNav.tsx
  app/components/AppsNav.tsx
  app/components/SideNav.tsx
  app/components/shared/ReactComponent.tsx
Labels: bundle release, react

#3682 port Studio Editor to React
  app/app-services.ts
  app/components-react/index.ts
  app/components-react/root/StudioEditor.m.less
  app/components-react/root/StudioEditor.tsx
  app/components/StudioEditor.vue
  app/components/StudioEditor.vue.ts
  app/components/StudioModeControls.vue
  app/components/StudioModeControls.vue.ts
  app/components/editor/elements/Display.tsx
  app/components/shared/ReactComponent.tsx
  app/services/editor.ts
Labels: react

#3691 Port AppsNav to React
  app/app-services.ts
  app/components-react/index.ts
  app/components-react/sidebar/AppsNav.m.less
  app/components-react/sidebar/AppsNav.tsx
  app/components/AppsNav.tsx
  app/components/SideNav.tsx
  app/components/shared/ReactComponent.tsx
  app/services/platform-apps/index.ts
Labels: bundle release, react

#3710 Add recurring variation to alert box
  app/i18n/en-US/widget-alertbox.json
  app/services/widgets/settings/alert-box/alert-box-data.ts
Labels: bundle release
