Repository streamlabs/desktop, pull requests merged in 2021-12, with the labels that each got.

#3922 Update Patch Notes
  app/services/patch-notes/notes.ts
Labels: bundle release

#3909 Fix width on name field in AddTabModal
  app/components/pages/AddTabModal.tsx
Labels: bug, bundle release

#3910 Fix border on onboarding buttons
  app/components/pages/onboarding-steps/Common.m.less
Labels: bug, bundle release

#3924 fix Use Different Title Overriding Simple Settings Title When Advanced Settings is Off
  app/components-react/windows/go-live/useGoLiveSettings.ts
Labels: bug

#3925 Showing Invalid Facebook Options in Edit Stream Window
  app/components-react/windows/go-live/PlatformSettings.tsx
Labels: bug

#3927 Fix infinite loading in the stream scheduler
  app/components-react/pages/stream-scheduler/useStreamScheduler.tsx
Labels: bug

#3892 Redesign SourceShowcase Window
  app/components-react/index.ts
  app/components-react/store/store.ts
  app/components-react/windows/AdvancedStatistics.m.less
  app/components-react/windows/AdvancedStatistics.tsx
  app/components-react/windows/go-live/EditStreamWindow.tsx
  app/components-react/windows/go-live/GoLiveSettings.tsx
  app/components-react/windows/sharedComponentsLibrary/SharedComponentsLibrary.tsx
  app/components-react/windows/source-showcase/SourceGrid.tsx
  app/components-react/windows/source-showcase/SourceShowcase.m.less
  app/components-react/windows/source-showcase/SourceTag.tsx
  app/components-react/windows/source-showcase/index.tsx
  app/components-react/windows/source-showcase/useSourceShowcase.tsx
  app/components/editor/elements/SourceSelector.vue.ts
  app/components/shared/ReactComponentList.tsx
  app/components/windows/SourcesShowcase.vue
  app/components/windows/SourcesShowcase.vue.ts
  app/i18n/en-US/sources.json
  app/services/customization.ts
  app/services/sources/sources-api.ts
  app/services/sources/sources-data.ts
  app/services/sources/sources.ts
  app/services/widgets/widgets-data.ts
  app/services/windows.ts
  app/styles/antd/antd.less
  test/helpers/modules/sources.ts
  test/regular/notifications.ts
Labels: bundle release

#3937 Source Showcase Fixes
  app/components-react/windows/source-showcase/SourceGrid.tsx
  app/components-react/windows/source-showcase/SourceShowcase.m.less
  app/components-react/windows/source-showcase/SourceTag.tsx
  app/components-react/windows/source-showcase/index.tsx
  app/services/user/index.ts
  app/styles/antd/day-theme.lazy.less
  app/styles/antd/prime-light.lazy.less
Labels: bundle release

#3926 Change Chat Size Slider Back to Percent
  app/components-react/windows/settings/Appearance.tsx
  app/components-react/windows/settings/General.tsx
Labels: bug

#3930 Fix copy/paste hotkeys for different keyboard layouts
  app/services/shortcuts.ts
Labels: bug

#3931 Fix YT resets the stream language when start streaming
  app/services/platforms/youtube.ts
Labels: bug

#3939 Fix clipping in media source SupportList
  app/components-react/windows/source-showcase/index.tsx
Labels: bug, bundle release

#3717 Port Settings to React 5: Advanced
  app/components-react/obs/ObsForm.tsx
  app/components-react/windows/settings/Advanced.tsx
  app/components-react/windows/settings/pages.ts
  app/components-react/windows/sharedComponentsLibrary/DemoForm.tsx
  app/components/windows/settings/Settings.vue.ts
  test/helpers/modules/forms/base.ts
  test/helpers/modules/forms/form.ts
  test/regular/settings/advanced.ts
  test/regular/shared-components/components.ts
Labels: react

#3911 Port BrowserView to React
  app/components-react/index.ts
  app/components-react/shared/BrowserView.tsx
  app/components/editor/elements/Browser.tsx
  app/components/editor/elements/LegacyEvents.tsx
  app/components/pages/AlertboxLibrary.tsx
  app/components/pages/BrowseOverlays.vue
  app/components/pages/BrowseOverlays.vue.ts
  app/components/pages/PlatformAppStore.vue
  app/components/pages/PlatformAppStore.vue.ts
  app/components/shared/BrowserView.tsx
  app/components/shared/ReactComponentList.tsx
  app/components/windows/RecentEvents.vue
  app/components/windows/RecentEvents.vue.ts
  app/components/windows/settings/StreamSettings.tsx
Labels: bundle release, react

#3944 Fix browser properties for App source
  app/services/sources/sources.ts
Labels: bug

#3950 Fix essential widgets on logged out state
  app/components-react/windows/source-showcase/SourceGrid.tsx
Labels: bug, bundle release
