Repository streamlabs/desktop, pull requests merged in 2021-04, with the labels that each got.

#3413 remove references to Mixer and add FB to list for ViewerCount
  app/i18n/en-US/sources.json
  app/i18n/en-US/widget-tip-jar.json
  app/i18n/en-US/widgets.json
  app/services/widgets/widgets-data.ts
Labels: bundle release

#3400 filter localstorage on load for persistent stateful service
  app/services/core/persistent-stateful-service.ts
  app/services/notifications/notifications.ts
Labels: bundle release

#3411 Hide overlay hotkeys on mac
  app/services/hotkeys.ts
Labels: bundle release

#3410 Fix video placeholder jank in onboarding
  app/components/pages/onboarding-steps/HardwareSetup.m.less
Labels: bundle release

#3412 Disable selective recording in context menu if feature isn't active
  app/util/menus/EditMenu.ts
Labels: bundle release

#3388 Add IconLibrary Source
  app/app-services.ts
  app/components-react/index.ts
  app/components-react/shared/ModalLayout.tsx
  app/components-react/shared/inputs/FileInput.tsx
  app/components-react/shared/inputs/index.ts
  app/components-react/windows/IconLibraryProperties.m.less
  app/components-react/windows/IconLibraryProperties.tsx
  app/components/obs/inputs/ObsInput.ts
  app/components/shared/ReactComponent.tsx
  app/components/windows/AddSource.vue.ts
  app/components/windows/ChildWindow.tsx
  app/components/windows/SourcesShowcase.vue
  app/components/windows/SourcesShowcase.vue.ts
  app/components/windows/settings/OverlaySettings.tsx
  app/i18n/en-US/sources.json
  app/services/customization.ts
  app/services/scene-collections/nodes/overlays/icon-library.ts
  app/services/scene-collections/nodes/overlays/slots.ts
  app/services/scene-collections/overlays.ts
  app/services/sources/properties-managers/icon-library-manager.ts
  app/services/sources/sources-api.ts
  app/services/sources/sources.ts
  app/services/windows.ts
  app/styles/antd/day-theme.lazy.less
  app/styles/antd/night-theme.lazy.less
  app/styles/antd/prime-dark.lazy.less
  app/styles/antd/prime-light.lazy.less
  app/styles/inputs.less
Labels: bundle release, ready for review

#3418 Change FB chat url and make description required
  app/components/windows/go-live/CommonPlatformFields.tsx
  app/services/chat.ts
  app/services/platforms/facebook.ts
Labels: bundle release

#3420 Fix opening app source properties
  app/services/sources/sources.ts
Labels: bundle release

#3421 Fix tests
  app/services/platforms/twitch.ts
  app/services/utils.ts
  test/helpers/spectron/user.ts
Labels: bundle release

#3429 add workspace settings to find typescript instance
  .vscode/settings.json
Labels: bundle release

#3430 Do not prevent FB going live in case of errors in groups API
  app/components/windows/go-live/platforms/FacebookEditStreamInfo.tsx
  app/services/platforms/facebook.ts
Labels: bundle release

#3428 fix some chat resize jank
  app/components/windows/Main.vue
  app/components/windows/Main.vue.ts
Labels: bundle release

#3431 use extends for react tsconfig
  app/components-react/tsconfig.json
Labels: bundle release

#3419 Add Support for Several New Train Types
  app/services/streamlabels/index.ts
Labels: bundle release

#3423 fixing several minifeed bugs
  app/i18n/en-US/recent-events.json
  app/services/recent-events.ts
Labels: bundle release

#3432 Fix Search Term Highlighting Style
  app/components/shared/SearchablePages.m.less
Labels: bundle release

#3439 add some context to error logs
  app/components/windows/Main.vue.ts
  app/services/platforms/facebook.ts
  app/services/streaming/streaming.ts
  app/services/video-encoding-optimizations/video-encoding-optimizations.ts
Labels: bundle release

#3436 fix hooks for Chat.tsx
  app/components-react/root/Chat.tsx
Labels: bundle release

#3438 Prevent duplication of media assets when exporting overlays
  app/i18n/en-US/settings.json
  app/services/scene-collections/nodes/overlays/icon-library.ts
  app/services/scene-collections/nodes/overlays/image.ts
  app/services/scene-collections/nodes/overlays/root.ts
  app/services/scene-collections/nodes/overlays/scenes.ts
  app/services/scene-collections/nodes/overlays/slots.ts
  app/services/scene-collections/nodes/overlays/video.ts
Labels: bundle release

#3443 fix prepopulate platform error
  app/services/streaming/streaming.ts
Labels: bundle release

#3444 add platform to streaming error in another spot
  app/services/streaming/streaming.ts
Labels: bundle release

#3446 Fix Facebook description
  app/components-react/windows/go-live/CommonPlatformFields.tsx
  app/components/windows/go-live/CommonPlatformFields.tsx
Labels: bundle release

#3316 Port PerformanceMetrics to React
  app/components-react/index.ts
  app/components-react/shared/PerformanceMetrics.m.less
  app/components-react/shared/PerformanceMetrics.tsx
  app/components/PerformanceMetrics.vue
  app/components/PerformanceMetrics.vue.ts
  app/components/StudioFooter.vue
  app/components/StudioFooter.vue.ts
  app/components/shared/ReactComponent.tsx
  app/components/windows/AdvancedStatistics.m.less
  app/components/windows/AdvancedStatistics.tsx
  app/services/customization.ts
  app/services/performance.ts
  app/services/windows.ts
Labels: bundle release, react, ready for review

#3408 Port NavTools to React
  app/app-services.ts
  app/components-react/index.ts
  app/components-react/sidebar/NavTools.tsx
  app/components/NavTools.tsx
  app/components/SideNav.tsx
  app/components/shared/ReactComponent.tsx
  app/services/transitions.ts
Labels: bundle release, react

#3449 add eslint hooks plugin
  .eslintrc.js
  app/services/hosts.ts
  app/services/utils.ts
  package.json
  yarn.lock
Labels: bundle release

#3454 Clear up master by reverting 2 ports
  app/app-services.ts
  app/components-react/index.ts
  app/components-react/shared/PerformanceMetrics.m.less
  app/components-react/shared/PerformanceMetrics.tsx
  app/components-react/sidebar/NavTools.tsx
  app/components/NavTools.tsx
  app/components/PerformanceMetrics.vue
  app/components/PerformanceMetrics.vue.ts
  app/components/SideNav.tsx
  app/components/StudioFooter.vue
  app/components/StudioFooter.vue.ts
  app/components/shared/ReactComponent.tsx
  app/components/windows/AdvancedStatistics.m.less
  app/components/windows/AdvancedStatistics.tsx
  app/services/customization.ts
  app/services/performance.ts
  app/services/transitions.ts
  app/services/windows.ts
Labels: bundle release

#3450 Fix YT resetting tags
  app/services/platforms/youtube.ts
Labels: bundle release

#3458 Fix jank in performance metrics background color
  app/components-react/shared/PerformanceMetrics.m.less
Labels: bundle release

#3460 Fix button highlighting in AdvancedStatistics
  app/components-react/shared/PerformanceMetrics.m.less
  app/components/windows/AdvancedStatistics.m.less
Labels: bundle release

#3464 Make TwitchGameSelector required
  app/components-react/windows/go-live/platforms/TwitchEditStreamInfo.tsx
  app/components-react/windows/go-live/useGoLiveSettings.ts
Labels: bundle release

#3467 Remove errant comma
  app/components-react/windows/go-live/platforms/TwitchEditStreamInfo.tsx
Labels: bundle release

#3474 Fix YT errors
  app/services/streaming/stream-error.ts
Labels: bundle release

#3470 don't fetch game image for facebook
  app/components-react/windows/go-live/GameSelector.tsx
Labels: bundle release

#3473 make tags optional
  app/components-react/windows/go-live/platforms/TwitchEditStreamInfo.tsx
Labels: bundle release

#3472 ensure tweet state is false when unlinked or logged out
  app/services/integrations/twitter.ts
Labels: bundle release

#3471 error when tweet fails
  app/components-react/windows/go-live/GoLiveError.tsx
  app/services/integrations/twitter.ts
Labels: bundle release

#3477 fix react keys error on twitch stream info
  app/components-react/windows/go-live/platforms/TwitchEditStreamInfo.tsx
Labels: bundle release

#3483 Fix lodash imports
  app/components-react/hooks.ts
  app/components-react/hooks/useStateManager.tsx
  app/components-react/shared/Translate.tsx
  app/components-react/shared/VueComponent.tsx
  app/components-react/shared/inputs/InputWrapper.tsx
  app/components-react/shared/inputs/TagsInput.tsx
  app/components-react/shared/inputs/inputs.ts
  app/components-react/windows/go-live/Twitter.tsx
  app/components-react/windows/go-live/platforms/TwitchTagsInput.tsx
  app/components-react/windows/go-live/useGoLiveSettings.ts
  app/components/GLVolmeters.tsx
  app/components/windows/go-live/CommonPlatformFields.tsx
  app/services/platforms/youtube.ts
  app/services/recent-events.ts
  app/services/selection/global-selection.ts
  app/services/sources/source.ts
  app/services/streaming/streaming-view.ts
  app/services/streaming/streaming.ts
  test/helpers/api-client.ts
  test/helpers/spectron/runner-utils.ts
Labels: bundle release

#3492 fix crashing when refreshing unpacked apps
  app/services/platform-apps/container-manager.ts
Labels: bundle release

#3494 remove margin from navtools
  app/components/shared/ReactComponent.tsx
Labels: bundle release

#3485 remove references to cloudbot
  app/components/pages/Chatbot.vue
  app/components/pages/Chatbot.vue.ts
  app/components/windows/Main.vue.ts
  app/services/incremental-rollout.ts
  app/services/navigation.ts
Labels: bundle release
