Repository streamlabs/desktop, pull requests merged in 2021-07, with the labels that each got.

#3563 Port AdvancedStatistics to React
  app/app-services.ts
  app/components-react/hooks.ts
  app/components-react/index.ts
  app/components-react/root/StartStreamingButton.tsx
  app/components-react/shared/ModalLayout.tsx
  app/components-react/shared/PerformanceMetrics.tsx
  app/components-react/windows/AdvancedStatistics.m.less
  app/components-react/windows/AdvancedStatistics.tsx
  app/components/GlobalSyncStatus.vue
  app/components/GlobalSyncStatus.vue.ts
  app/components/StudioFooter.vue.ts
  app/components/shared/ReactComponent.tsx
  app/components/windows/AdvancedStatistics.tsx
  app/services/media-backup.ts
  app/services/performance.ts
  app/services/streaming/streaming-view.ts
  app/services/touch-bar.ts
  app/services/windows.ts
  test/regular/media-backup.ts
  test/regular/troubleshooter.ts
Labels: bundle release, react

#3586 Port RenameSource to React
  app/components-react/index.ts
  app/components-react/windows/RenameSource.tsx
  app/components/shared/ReactComponent.tsx
  app/components/windows/RenameSource.vue
  app/components/windows/RenameSource.vue.ts
  app/services/windows.ts
  test/regular/sources.ts
Labels: react

#3595 Fix Editor translation in SideNav
  app/components/SideNav.tsx
Labels: bug, bundle release

#3607 Fix clipping on transition settings modal
  app/components/windows/SceneTransitions.vue
Labels: Next Release

#3608 Add option to use Twitch URL in tweet body
  app/components-react/windows/go-live/Twitter.tsx
  app/i18n/en-US/twitter.json
  app/services/integrations/twitter.ts
Labels: bundle release

#3606 Port AdvancedStatistics to React
  app/app-services.ts
  app/components-react/hooks.ts
  app/components-react/index.ts
  app/components-react/root/StartStreamingButton.tsx
  app/components-react/shared/ModalLayout.tsx
  app/components-react/shared/PerformanceMetrics.tsx
  app/components-react/windows/AdvancedStatistics.m.less
  app/components-react/windows/AdvancedStatistics.tsx
  app/components/GlobalSyncStatus.vue
  app/components/GlobalSyncStatus.vue.ts
  app/components/StudioFooter.vue.ts
  app/components/shared/ReactComponent.tsx
  app/components/windows/AdvancedStatistics.tsx
  app/services/media-backup.ts
  app/services/performance.ts
  app/services/streaming/streaming-view.ts
  app/services/touch-bar.ts
  app/services/windows.ts
  test/regular/media-backup.ts
  test/regular/troubleshooter.ts
Labels: bundle release, react

#3604 updated troubleshooter tests
  test/regular/notifications.ts
Labels: bundle release

#3601 Port RenameSource to React
  app/components-react/index.ts
  app/components-react/windows/RenameSource.tsx
  app/components/shared/ReactComponent.tsx
  app/components/windows/RenameSource.vue
  app/components/windows/RenameSource.vue.ts
  app/services/windows.ts
  test/regular/sources.ts
Labels: bundle release, react

#3613 Prevent multiple simultaneous theme installs
  app/components/pages/BrowseOverlays.vue.ts
Labels: bundle release

#3615 Increase contrast of Obsidian Prime
  app/styles/antd/prime-dark.lazy.less
  app/themes.g.less
Labels: bundle release

#3617 Fix footer creep on highlighter and grow tab
  app/components-react/pages/Highlighter.m.less
  app/components-react/pages/grow/Grow.m.less
Labels: bug, bundle release

#3598 Update kraken endpoints to use helix
  app/services/platforms/twitch.ts
Labels: bundle release

#3622 Fix selective recording projector in fullscreen
  app/components/windows/Projector.vue
  app/util/menus/EditMenu.ts
Labels: bug, bundle release

#3628 Patch Notes 1.3.0
  app/services/patch-notes/notes.ts
  scripts/react-progress.js
Labels: bundle release

#3629 Update kraken endpoints to use helix
  app/services/platforms/twitch.ts
Labels: bundle release

#3631 Prevent Grow tab form submission if invalidated
  app/components-react/pages/grow/Grow.tsx
Labels: bug, bundle release

#3636 Add Polls Widget
  app/app-services.ts
  app/components/editor/elements/SourceSelector.vue.ts
  app/components/widgets/Poll.tsx
  app/components/windows/SourcesShowcase.vue.ts
  app/i18n/en-US/widget-poll.json
  app/i18n/fallback.ts
  app/services/utils.ts
  app/services/widgets/settings/poll.ts
  app/services/widgets/widgets-data.ts
  app/services/windows.ts
Labels: bundle release

#3642 Add arrow in sidebar for non-prime users
  app/components/SideNav.tsx
Labels: bug, bundle release

#3593 Port NotificationsArea to React
  app/components-react/index.ts
  app/components-react/root/NotificationsArea.m.less
  app/components-react/root/NotificationsArea.tsx
  app/components/NotificationsArea.vue.ts
  app/components/StudioFooter.vue.ts
  app/components/shared/ReactComponent.tsx
Labels: bundle release, react

#3646 Fix jank in Poll image and notif area
  app/app-services.ts
  app/components-react/root/NotificationsArea.tsx
  app/components/widgets/Poll.tsx
  app/i18n/en-US/widget-poll.json
  app/services/platforms/twitch.ts
  app/services/platforms/twitch/scopes.ts
  app/services/utils.ts
Labels: bundle release

#3647 Fix display overlap with large chats
  app/components/windows/Main.vue
Labels: bug, bundle release

#3657 show promise rejections from async action calls
  app/services/api/rpc-api.ts
Labels: bundle release

#3656 import filters from OBS on global audio sources
  app/services/obs-importer.ts
Labels: bundle release

#3655 highlighter i18n
  app/components-react/highlighter/BlankSlate.tsx
  app/components-react/highlighter/ClipPreview.tsx
  app/components-react/highlighter/ClipTrimmer.tsx
  app/components-react/highlighter/ExportModal.tsx
  app/components-react/highlighter/PreviewModal.tsx
  app/components-react/highlighter/YoutubeUpload.tsx
  app/components-react/pages/Highlighter.tsx
  app/components-react/shared/Translate.tsx
  app/i18n/en-US/highlighter.json
  app/i18n/fallback.ts
  app/services/highlighter/errors.ts
  app/services/highlighter/index.ts
Labels: bundle release

#3658 Increase minEditorSize to account for pinned statistics
  app/components/windows/Main.vue.ts
Labels: bundle release

#3659 Add guard clause on changing minEditorWidth
  app/components/windows/Main.vue.ts
Labels: bundle release
