Repository streamlabs/desktop, pull requests merged in 2021-03, with the labels that each got.

#3340 React shared components
  .eslintrc.js
  app/app-services.ts
  app/app.g.less
  app/components-react/hooks.ts
  app/components-react/index.d.ts
  app/components-react/modals.ts
  app/components-react/shared/ModalLayout.m.less
  app/components-react/shared/ModalLayout.tsx
  app/components-react/shared/PlatformLogo.m.less
  app/components-react/shared/PlatformLogo.tsx
  app/components-react/shared/Scrollable.tsx
  app/components-react/shared/Translate.tsx
  app/components-react/shared/VueComponent.tsx
  app/components-react/shared/inputs/CheckboxInput.tsx
  app/components-react/shared/inputs/Form.tsx
  app/components-react/shared/inputs/InputWrapper.tsx
  app/components-react/shared/inputs/ListInput.tsx
  app/components-react/shared/inputs/NumberInput.tsx
  app/components-react/shared/inputs/SliderInput.tsx
  app/components-react/shared/inputs/SwitchInput.tsx
  app/components-react/shared/inputs/TagsInput.tsx
  app/components-react/shared/inputs/TextAreaInput.tsx
  app/components-react/shared/inputs/TextInput.tsx
  app/components-react/shared/inputs/index.ts
  app/components-react/shared/inputs/inputs.ts
  app/components-react/windows/NameFolder.tsx
  app/components/shared/ReactComponent.tsx
  app/components/windows/go-live/GoLiveError.tsx
  app/services/integrations/twitter.ts
  app/services/platforms/facebook.ts
  app/services/streaming/stream-error.ts
  app/styles/animations.less
  app/styles/antd.less
  app/styles/colors.less
  app/themes.g.less
  package.json
  scripts/postinstall.js
  test/regular/filters.js
  test/regular/onboarding.ts
  webpack.base.config.js
  yarn.lock
Labels: react

#3343 Build CC Expiration flow
  app/components/NotificationsArea.vue.ts
  app/i18n/en-US/promotional-copy.json
  app/services/core/persistent-stateful-service.ts
  app/services/notifications/notifications.ts
  app/services/user/index.ts
Labels: bundle release

#3347 Build CC Expiration flow
  app/components/NotificationsArea.vue.ts
  app/i18n/en-US/promotional-copy.json
  app/services/core/persistent-stateful-service.ts
  app/services/notifications/notifications.ts
  app/services/user/index.ts
Labels: bundle release

#3332 Port Chat to React
  app/app-services.ts
  app/components-react/index.d.ts
  app/components-react/index.ts
  app/components-react/root/Chat.m.less
  app/components-react/root/Chat.tsx
  app/components/Chat.vue
  app/components/Chat.vue.ts
  app/components/LiveDock.vue
  app/components/LiveDock.vue.ts
  app/components/shared/ReactComponent.tsx
Labels: bundle release, react

#3337 Port TitleBar to React
  app/components-react/index.ts
  app/components-react/shared/KevinSvg.tsx
  app/components-react/shared/TitleBar.m.less
  app/components-react/shared/TitleBar.tsx
  app/components/TitleBar.tsx
  app/components/shared/ReactComponent.tsx
  app/components/windows/ChildWindow.tsx
  app/components/windows/Main.vue
  app/components/windows/Main.vue.ts
  app/components/windows/OneOffWindow.vue
  app/components/windows/OneOffWindow.vue.ts
  app/services/customization.ts
Labels: bundle release, react

#3365 Bring back Vue Chat
  app/components-react/root/Chat.tsx
  app/components/Chat.vue
  app/components/Chat.vue.ts
  app/components/LiveDock.vue
  app/components/LiveDock.vue.ts
  app/components/shared/ReactComponent.tsx
Labels: bundle release

#3367 Bring back Vue Chat
  app/components-react/root/Chat.tsx
  app/components/Chat.vue
  app/components/Chat.vue.ts
  app/components/LiveDock.vue
  app/components/LiveDock.vue.ts
  app/components/shared/ReactComponent.tsx
Labels: bundle release

#3375 fix windows display scaling with electron 10
  app/services/windows.ts
Labels: bundle release

#3381 YT: fix streaming to the scheduled broadcasts with a `madeForKids` flag
  app/services/platforms/youtube.ts
Labels: bundle release

#3359 Add support for FB Gifted Supporters
  app/components/widgets/AlertBox.vue.ts
  app/i18n/en-US/widget-alertbox.json
  app/services/widgets/settings/alert-box/alert-box-data.ts
Labels: bundle release

#3389 remove FM filter from sources properly
  app/services/scene-collections/nodes/sources.ts
Labels: bundle release

#3301 Fix system clipboard overwriting copied sources
  app/services/clipboard.ts
Labels: bundle release

#3376 Add theme compatibility to antd
  app/app.g.less
  app/components/windows/ChildWindow.tsx
  app/components/windows/Main.vue.ts
  app/components/windows/OneOffWindow.vue.ts
  app/index.d.ts
  app/styles/antd.less
  app/styles/antd/day-theme.lazy.less
  app/styles/antd/index.ts
  app/styles/antd/night-theme.lazy.less
  app/styles/antd/prime-dark.lazy.less
  app/styles/antd/prime-light.lazy.less
  package.json
  webpack.base.config.js
  yarn.lock
Labels: bundle release, react

#3361 fix app source load issue
  app/services/platform-apps/index.ts
Labels: bundle release

#3368 Add support for dynamic props for React in Vue cases
  app/components/Chat.vue
  app/components/Chat.vue.ts
  app/components/LiveDock.vue
  app/components/LiveDock.vue.ts
  app/components/shared/ReactComponent.tsx
Labels: bundle release, react

#3320 Port Display to React
  app/app-services.ts
  app/components-react/index.d.ts
  app/components-react/index.ts
  app/components-react/shared/Display.tsx
  app/components/StudioEditor.vue
  app/components/StudioEditor.vue.ts
  app/components/editor/elements/RecordingPreview.tsx
  app/components/editor/elements/StreamPreview.tsx
  app/components/pages/onboarding-steps/HardwareSetup.tsx
  app/components/shared/Display.vue
  app/components/shared/Display.vue.ts
  app/components/shared/ReactComponent.tsx
  app/components/windows/AddSource.vue
  app/components/windows/AddSource.vue.ts
  app/components/windows/BrowserSourceInteraction.tsx
  app/components/windows/OverlayWindow.vue
  app/components/windows/OverlayWindow.vue.ts
  app/components/windows/Projector.vue
  app/components/windows/Projector.vue.ts
  app/components/windows/SourceFilters.vue
  app/components/windows/SourceFilters.vue.ts
  app/components/windows/SourceProperties.vue
  app/components/windows/SourceProperties.vue.ts
  app/components/windows/WidgetEditor.vue
  app/components/windows/WidgetEditor.vue.ts
  app/services/customization.ts
Labels: bundle release, react

#3401 Fix watcher eagerly refreshing components
  app/components/shared/ReactComponent.tsx
Labels: bundle release, react

#3402 Fix widget editor css
  app/components/windows/WidgetEditor.vue
Labels: bundle release, react

#3404 Fix Projector in full screen mode
  app/components/windows/Projector.vue
Labels: bundle release, react

#3373 fix game overlay position on edge of screen resetting
  app/services/game-overlay/index.ts
Labels: bundle release

#3374 port hotkeys to strict nulls
  app/services/hotkeys.ts
  strict-null-check-files/hotekys.json
Labels: bundle release

#3397 explicitly set streaming server when recommended settings are enabled
  app/services/platforms/facebook.ts
  app/services/platforms/twitch.ts
  app/services/platforms/youtube.ts
Labels: bundle release

#3311 Port PatchNotes to React
  app/app-services.ts
  app/components-react/index.ts
  app/components-react/pages/PatchNotes.m.less
  app/components-react/pages/PatchNotes.tsx
  app/components/pages/PatchNotes.vue.ts
  app/components/shared/ReactComponent.tsx
  app/components/windows/Main.vue.ts
Labels: bundle release, react, ready for review

#3403 fix empty checkboxes in Jar widget
  app/components/widgets/TipJar.vue.ts
  app/i18n/en-US/widget-tip-jar.json
  app/i18n/en-US/widgets.json
Labels: bundle release

#3406 Fix custom code css
  app/components/windows/WidgetEditor.vue
Labels: bundle release

#3409 Fix Display lifecycle method
  app/components-react/shared/Display.tsx
Labels: bundle release, react
