Repository streamlabs/desktop, pull requests merged in 2022-02, with the labels that each got.

#3921 Port dshow_input to React
  app/components-react/obs/ObsForm.tsx
  app/services/sources/sources.ts
  test/regular/sources.ts
Labels: react

#3920 Port openvr_capture to React
  app/services/sources/sources.ts
Labels: react

#3918 Port ffmpeg_source to React
  app/services/sources/sources.ts
  test/regular/sources.ts
Labels: react

#4009 Fix disappearing browserUrl in some cases
  app/components-react/pages/layout-editor/hooks.ts
Labels: bug, bundle release

#3919 Port game_capture to React
  app/services/sources/sources.ts
  test/regular/sources.ts
Labels: react

#3972 Port LegacyEvents to React
  app/components-react/editor/elements/LegacyEvents.tsx
  app/components-react/index.ts
  app/components-react/shared/BrowserView.tsx
  app/components/editor/elements/LegacyEvents.tsx
  app/components/editor/elements/index.ts
  app/components/shared/ReactComponentList.tsx
  app/services/user/index.ts
Labels: bundle release, react

#3917 Port browser_source to React
  app/components-react/obs/ObsForm.tsx
  app/components-react/windows/SourceProperties.tsx
  app/services/sources/sources.ts
  test/regular/sources.ts
Labels: react

#4001 More AdvancedAudio Fixes
  app/components-react/windows/advanced-audio/GlobalSettings.tsx
  app/components-react/windows/advanced-audio/SourceSettings.tsx
  app/components-react/windows/advanced-audio/index.tsx
  app/i18n/en-US/audio.json
  app/services/settings/settings.ts
Labels: bug, bundle release

#3989 Fix source showcase padding and window capture copy
  app/components-react/windows/source-showcase/SourceGrid.tsx
  app/i18n/en-US/sources.json
  app/services/sources/sources-data.ts
  app/services/widgets/widgets-data.ts
Labels: bug, bundle release

#4015 Fix multiple VOD Track error messages
  app/components-react/windows/advanced-audio/SourceSettings.tsx
  app/components-react/windows/advanced-audio/index.tsx
  app/i18n/en-US/audio.json
Labels: bug, bundle release

#3915 Port image_source to React
  app/services/sources/sources.ts
  test/regular/sources.ts
Labels: react

#4018 Re-add Follow Goals for Trovo
  app/services/sources/sources.ts
  app/services/widgets/widgets-data.ts
Labels: bug, bundle release

#3938 Port RemoteControl settings to React
  app/app-services.ts
  app/components-react/windows/settings/RemoteControl.tsx
  app/components-react/windows/settings/pages.ts
  app/components/windows/settings/RemoteControlQRCode.vue
  app/components/windows/settings/RemoteControlQRCode.vue.ts
  app/components/windows/settings/RemoteControlSettings.vue
  app/components/windows/settings/RemoteControlSettings.vue.ts
  app/components/windows/settings/Settings.vue
  app/components/windows/settings/Settings.vue.ts
  app/i18n/en-US/remote-control.json
  package.json
  yarn.lock
Labels: react

#3916 Port color_source to React
  app/services/sources/sources.ts
  test/regular/sources.ts
Labels: react

#4028 Add GameWidget
  app/components-react/widgets/GameWidget.tsx
  app/components-react/widgets/common/WidgetWindow.tsx
  app/components-react/widgets/common/useWidget.tsx
  app/i18n/en-US/widget-game.json
  app/i18n/fallback.ts
  app/services/sources/sources.ts
  app/services/widgets/widget-source.ts
  app/services/widgets/widgets-config.ts
  app/services/widgets/widgets-data.ts
  app/services/widgets/widgets.ts
  media/source-demos/day/game-widget.png
  media/source-demos/night/game-widget.png
Labels: bundle release

#4008 Port SceneSelector to React
  app/app-services.ts
  app/components-react/editor/elements/SceneSelector.m.less
  app/components-react/editor/elements/SceneSelector.tsx
  app/components-react/editor/elements/SceneSelectorElement.tsx
  app/components-react/hooks/useTree.tsx
  app/components-react/index.ts
  app/components-react/shared/HelpTip.m.less
  app/components-react/shared/HelpTip.tsx
  app/components/editor/elements/SceneSelector.vue
  app/components/editor/elements/SceneSelector.vue.ts
  app/components/editor/elements/SceneSelectorElement.tsx
  app/components/editor/elements/index.ts
  app/components/shared/HelpTip.tsx
  app/components/shared/ReactComponentList.tsx
  test/helpers/modules/scenes.ts
  test/regular/obs-importer.ts
Labels: bundle release, react

#4030 port emote wall widget to react
  app/components-react/widgets/EmoteWall.tsx
  app/components-react/widgets/common/WidgetWindow.tsx
  app/services/sources/sources.ts
  app/services/widgets/widgets-config.ts
Labels: bundle release

#4039 Fix audio playback in MediaGallery
  app/components-react/windows/MediaGallery.tsx
Labels: bug, bundle release

#3936 Port experimental settings to React
  app/components-react/windows/settings/Experimental.tsx
  app/components-react/windows/settings/pages.ts
  app/components/windows/settings/ExperimentalSettings.vue
  app/components/windows/settings/ExperimentalSettings.vue.ts
  app/components/windows/settings/Settings.vue
  app/components/windows/settings/Settings.vue.ts
Labels: react

#4046 Fix SceneSelector dropdown rendering above component
  app/components-react/editor/elements/SceneSelector.m.less
  app/components-react/editor/elements/SceneSelector.tsx
Labels: bug

#4048 Fix top layout dropdown overlap
  app/components-react/editor/elements/SceneSelector.m.less
  app/components/editor/layouts/Classic.tsx
  app/components/editor/layouts/Default.tsx
  app/components/editor/layouts/FourByFour.tsx
  app/components/editor/layouts/Layouts.m.less
  app/components/editor/layouts/Pyramid.tsx
Labels: bug
