Repository streamlabs/desktop, pull requests merged in 2022-05, with the labels that each got.

#4137 Fix unreactive mute button in AdvancedAudio
  app/components-react/windows/advanced-audio/SourceSettings.tsx
Labels: bug

#4140 Port Alertbox Library to React
  app/app-services.ts
  app/components-react/index.ts
  app/components-react/pages/AlertboxLibrary.tsx
  app/components-react/shared/BrowserView.tsx
  app/components/pages/AlertboxLibrary.tsx
  app/components/shared/ReactComponentList.tsx
  app/components/windows/Main.vue.ts
  app/services/user/index.ts
Labels: react

#4145 Port BrowseOverlays to React
  app/components-react/index.ts
  app/components-react/pages/BrowseOverlays.tsx
  app/components/pages/BrowseOverlays.vue
  app/components/pages/BrowseOverlays.vue.ts
  app/components/shared/ReactComponentList.tsx
  app/components/windows/Main.vue.ts
  app/services/user/index.ts
Labels: react

#4146 Port PlatformAppStore to React
  app/app-services.ts
  app/components-react/index.ts
  app/components-react/pages/PlatformAppStore.tsx
  app/components/pages/PlatformAppStore.vue
  app/components/pages/PlatformAppStore.vue.ts
  app/components/shared/ReactComponentList.tsx
  app/components/windows/Main.vue.ts
  app/services/user/index.ts
Labels: react

#4151 Fix Themes and Apps loading
  app/components-react/pages/BrowseOverlays.tsx
  app/components-react/pages/PlatformAppStore.tsx
Labels: bug

#4143 Port PlatformMerge to React
  app/components-react/index.ts
  app/components-react/pages/PlatformMerge.tsx
  app/components/pages/PlatformMerge.tsx
  app/components/shared/ReactComponentList.tsx
  app/components/windows/Main.vue
  app/components/windows/Main.vue.ts
  app/i18n/en-US/facebook.json
Labels: react

#4153 Port PlatformApp Pages to React
  app/components-react/index.ts
  app/components-react/pages/PlatformAppMainPage.tsx
  app/components-react/shared/PlatformAppPageView.tsx
  app/components-react/windows/PlatformAppPopOut.tsx
  app/components/LiveDock.vue.ts
  app/components/PlatformAppPageView.vue
  app/components/PlatformAppPageView.vue.ts
  app/components/pages/PlatformAppMainPage.vue
  app/components/pages/PlatformAppMainPage.vue.ts
  app/components/shared/ReactComponentList.tsx
  app/components/windows/Main.vue.ts
  app/components/windows/PlatformAppPopOut.vue
  app/components/windows/PlatformAppPopOut.vue.ts
  app/services/windows.ts
Labels: react

#4157 Update macOS Icon
  media/images/icon-mac.icns
Labels: staging

#4158 Fix AppMainPage style
  app/components-react/pages/PlatformAppMainPage.tsx
  app/components-react/windows/PlatformAppPopOut.tsx
Labels: bug

#4159 Port GameOverlaySettings to React
  app/app-services.ts
  app/components-react/shared/inputs/SliderInput.tsx
  app/components-react/windows/settings/GameOverlay.tsx
  app/components-react/windows/settings/pages.ts
  app/components/windows/settings/GameOverlaySettings.tsx
  app/components/windows/settings/Settings.vue
  app/components/windows/settings/Settings.vue.ts
Labels: react

#4164 Fix Overlay Slider
  app/components-react/windows/settings/GameOverlay.tsx
Labels: bug

#4169 Fix modal height of transition settings
  app/components/windows/SceneTransitions.vue
Labels: staging

#4163 Port RecordingPreview and StreamPreview to React
  app/components-react/editor/elements/RecordingPreview.tsx
  app/components-react/editor/elements/StreamPreview.tsx
  app/components-react/index.ts
  app/components/editor/elements/RecordingPreview.tsx
  app/components/editor/elements/StreamPreview.tsx
  app/components/editor/elements/index.ts
  app/components/shared/ReactComponentList.tsx
Labels: react

#4171 Skip to News window if there are no unread notifs or if all unread no…
  app/components-react/root/NotificationsArea.tsx
  app/services/announcements.ts
  app/services/api/external-api/notifications/notifications.ts
  app/services/notifications/notifications-api.ts
  app/services/platform-apps/api/modules/notifications.ts
Labels: enhancement

#4160 Fix source transform
  app/components/windows/EditTransform.tsx
  app/services/editor.ts
Labels: bug

#4172 Fix reactivity of StreamPreview and RecordingPreview
  app/components-react/editor/elements/RecordingPreview.tsx
  app/components-react/editor/elements/StreamPreview.tsx
  app/components/shared/ReactComponentList.tsx
Labels: bug
