Repository streamlabs/desktop, pull requests merged in 2022-04, with the labels that each got.

#4068 Fix padding in WidgetTesters and SceneSelector
  app/app.g.less
  app/components-react/editor/elements/SceneSelector.tsx
Labels: bug

#4069 Add Facebook testers to Alertbox window
  app/services/widgets/settings/alert-box/index.ts
Labels: bug

#4083 add mac logic for default webcam
  app/services/sources/sources.ts
Labels: bug

#4076 Add News Window
  app/components-react/index.ts
  app/components-react/root/NewsBanner.m.less
  app/components-react/root/NewsBanner.tsx
  app/components-react/root/NotificationsArea.tsx
  app/components-react/windows/News.m.less
  app/components-react/windows/News.tsx
  app/components/shared/ReactComponentList.tsx
  app/components/windows/Main.vue
  app/components/windows/Main.vue.ts
  app/i18n/en-US/promotional-copy.json
  app/services/announcements.ts
  app/services/app/app.ts
  app/services/windows.ts
Labels: enhancement, bundle release

#4080 Port SideNav to React
  app/app-services.ts
  app/components-react/index.ts
  app/components-react/sidebar/AppsNav.m.less
  app/components-react/sidebar/AppsNav.tsx
  app/components-react/sidebar/NavTools.tsx
  app/components-react/sidebar/SideNav.m.less
  app/components-react/sidebar/SideNav.tsx
  app/components/SideNav.tsx
  app/components/shared/ReactComponentList.tsx
  app/components/windows/Main.vue.ts
Labels: react

#4094 Rename Twitch Game to Twitch Category
  app/components-react/windows/go-live/GameSelector.tsx
  app/i18n/en-US/twitch.json
Labels: enhancement

#4081 Port StudioFooter to React
  app/components-react/index.ts
  app/components-react/root/NotificationsArea.tsx
  app/components-react/root/StudioFooter.m.less
  app/components-react/root/StudioFooter.tsx
  app/components-react/root/TestWidgets.tsx
  app/components-react/shared/Display.tsx
  app/components-react/shared/PerformanceMetrics.tsx
  app/components/StudioFooter.vue
  app/components/StudioFooter.vue.ts
  app/components/shared/ReactComponentList.tsx
  app/components/windows/Main.vue
  app/components/windows/Main.vue.ts
  app/components/windows/OverlayWindow.vue
  app/components/windows/OverlayWindow.vue.ts
  app/services/streaming/streaming-view.ts
  app/services/windows.ts
Labels: react

#4098 Port DonationTicker to React
  app/components-react/widgets/DonationTicker.tsx
  app/components-react/widgets/common/WidgetWindow.tsx
  app/services/sources/sources.ts
  app/services/widgets/widgets-config.ts
Labels: react

#4113 Switch getTesters to a view
  app/components-react/root/TestWidgets.tsx
  app/components/widgets/TestButtons.vue.ts
  app/services/hosts.ts
  app/services/widgets/widgets.ts
Labels: bug, bundle release

#4120 Add Trovo followers to Grow tab
  app/components-react/pages/grow/Cards.tsx
  app/components-react/pages/grow/Grow.m.less
  app/services/grow/grow.ts
  app/services/platforms/trovo.ts
Labels: bug, enhancement, ready for review

#4119 add 7tv support to chatbox widget
  app/components/widgets/ChatBox.vue
  app/i18n/en-US/widget-chat-box.json
  app/services/widgets/settings/chat-box.ts
Labels: bundle release

#4088 Port AddSource to React
  app/components-react/index.ts
  app/components-react/windows/AddSource.m.less
  app/components-react/windows/AddSource.tsx
  app/components/shared/ReactComponentList.tsx
  app/components/windows/AddSource.vue
  app/components/windows/AddSource.vue.ts
  app/services/sources/sources.ts
  app/services/windows.ts
  test/helpers/modules/forms/form.ts
  test/helpers/modules/sources.ts
Labels: react

#4132 Select AlertBox by default in SourceShowcase
  app/components-react/windows/source-showcase/useSourceShowcase.tsx
Labels: enhancement

#4133 Only default to AlertBox if a user is logged in
  app/components-react/windows/source-showcase/useSourceShowcase.tsx
Labels: bug
