Repository streamlabs/desktop, pull requests merged in 2022-01, with the labels that each got.

#3968 Fix FB Tests
  test/regular/streaming/facebook.ts
  test/regular/streaming/multistream.ts
Labels: bug, bundle release

#3908 Port Minifeed to React
  app/components-react/editor/elements/BaseElement.m.less
  app/components-react/editor/elements/Minifeed.tsx
  app/components-react/editor/elements/RecentEvents.m.less
  app/components-react/editor/elements/RecentEvents.tsx
  app/components-react/editor/elements/hooks.tsx
  app/components-react/index.ts
  app/components/RecentEvents.tsx
  app/components/editor/elements/LegacyEvents.tsx
  app/components/editor/elements/MiniFeed.tsx
  app/components/editor/elements/index.ts
  app/components/shared/ReactComponent.tsx
  app/components/shared/ReactComponentList.tsx
  app/components/windows/GameOverlayEventFeed.tsx
Labels: bundle release, react

#3967 Fix app key
  app/components-react/windows/source-showcase/SourceGrid.tsx
Labels: bug, bundle release

#3970 Fix safe mode icon
  app/components-react/editor/elements/RecentEvents.tsx
Labels: bug, bundle release

#3935 Port Stream Settings to React
  app/components-react/obs/ObsForm.tsx
  app/components-react/store/store.ts
  app/components-react/windows/settings/Stream.m.less
  app/components-react/windows/settings/Stream.tsx
  app/components-react/windows/settings/pages.ts
  app/components/windows/settings/Settings.vue
  app/components/windows/settings/Settings.vue.ts
  app/components/windows/settings/StreamSettings.tsx
  test/helpers/modules/forms/base.ts
  test/regular/settings/streaming.ts
  test/regular/streaming/twitch.ts
  test/regular/themes.ts
Labels: react

#3975 Fix audio tracks in simple output
  app/services/audio/audio.ts
  app/services/settings/output/output-settings.ts
  app/services/settings/settings.ts
Labels: bug, bundle release

#3958 Remove duration from cut transitions
  app/components/TransitionSettings.vue
Labels: bug, bundle release

#3986 Temporarily skip transitions test
  test/regular/transitions.ts
Labels: bundle release

#3982 Port Projector to React
  app/components-react/index.ts
  app/components-react/shared/Display.tsx
  app/components-react/windows/Projector.m.less
  app/components-react/windows/Projector.tsx
  app/components/shared/ReactComponentList.tsx
  app/components/windows/Projector.vue
  app/components/windows/Projector.vue.ts
  app/services/windows.ts
Labels: bundle release, react

#3988 Redesign Prime onboarding step
  app/components/pages/onboarding-steps/Prime.m.less
  app/components/pages/onboarding-steps/Prime.tsx
  app/i18n/en-US/onboarding.json
  app/services/onboarding.ts
  test/helpers/modules/onboarding.ts
  test/regular/obs-importer.ts
  test/regular/onboarding.ts
  test/screentest/tests/onboarding.ts
Labels: bundle release

#3981 Port LayoutEditor to React
  app/app-services.ts
  app/components-react/index.ts
  app/components-react/pages/layout-editor/AddTabModal.tsx
  app/components-react/pages/layout-editor/LayoutEditor.m.less
  app/components-react/pages/layout-editor/LayoutEditor.tsx
  app/components-react/pages/layout-editor/SideBar.tsx
  app/components-react/pages/layout-editor/TopBar.tsx
  app/components-react/pages/layout-editor/hooks.ts
  app/components-react/shared/ModalLayout.tsx
  app/components-react/shared/inputs/CardInput.tsx
  app/components-react/widgets/common/LayoutInput.tsx
  app/components/pages/AddTabModal.tsx
  app/components/pages/LayoutEditor.tsx
  app/components/shared/ReactComponentList.tsx
  app/components/windows/Main.vue.ts
  app/services/layout/index.ts
Labels: bundle release, react

#3980 new integration
  app/app-services.ts
  app/components-react/editor/elements/RecentEvents.tsx
  app/components-react/root/StartStreamingButton.tsx
  app/components-react/shared/PlatformLogo.m.less
  app/components-react/shared/PlatformLogo.tsx
  app/components-react/widgets/ViewerCount.tsx
  app/components-react/widgets/useAlertBox.tsx
  app/components-react/windows/go-live/GameSelector.tsx
  app/components-react/windows/go-live/OptimizedProfileSwitcher.tsx
  app/components-react/windows/go-live/PlatformSettings.tsx
  app/components-react/windows/go-live/Twitter.tsx
  app/components-react/windows/go-live/platforms/PlatformSettingsLayout.tsx
  app/components-react/windows/go-live/platforms/TrovoEditStreamInfo.tsx
  app/components-react/windows/settings/Stream.tsx
  app/components/LiveDock.vue
  app/components/LiveDock.vue.ts
  app/components/pages/onboarding-steps/Connect.tsx
  app/components/widgets/TipJar.vue.ts
  app/components/windows/EventFilterMenu.tsx
  app/components/windows/settings/Settings.vue
  app/i18n/en-US/recent-events.json
  app/i18n/en-US/trovo.json
  app/i18n/en-US/widget-viewer-count.json
  app/i18n/fallback.ts
  app/services/chat.ts
  app/services/hosts.ts
  app/services/integrations/twitter.ts
  app/services/platforms/index.ts
  app/services/platforms/trovo.ts
  app/services/platforms/twitch.ts
  app/services/recent-events.ts
  app/services/restream.ts
  app/services/settings/streaming/stream-settings.ts
  app/services/streaming/streaming-api.ts
  app/services/streaming/streaming-view.ts
  app/services/streaming/streaming.ts
  app/services/streamlabels/index.ts
  app/services/user/index.ts
  app/services/utils.ts
  app/services/widgets/alerts-config.ts
  app/services/widgets/settings/alert-box/alert-box-data.ts
  app/services/widgets/settings/event-list.ts
  app/services/widgets/settings/stream-boss.ts
  app/services/widgets/widgets-data.ts
  app/styles/buttons.less
  app/styles/colors.less
  app/themes.g.less
  media/images/platforms/trovo-black.png
  media/images/platforms/trovo.png
  test/regular/streaming/facebook.ts
  test/regular/streaming/trovo.ts
Labels: work in progress

#4000 Add Superchat Goal
  app/app-services.ts
  app/components/widgets/goal/SuperchatGoal.tsx
  app/i18n/en-US/widgets.json
  app/services/widgets/settings/superchat-goal.ts
  app/services/widgets/widgets-data.ts
  app/services/windows.ts
Labels: bundle release

#3998 Port Media Gallery to React
  app/app-services.ts
  app/components-react/index.ts
  app/components-react/windows/MediaGallery.m.less
  app/components-react/windows/MediaGallery.tsx
  app/components/shared/ReactComponentList.tsx
  app/components/windows/MediaGallery.vue
  app/components/windows/MediaGallery.vue.ts
  app/services/media-gallery/media-gallery.ts
  app/services/windows.ts
Labels: bundle release, react

#4006 Fix SpinWheel button reactivity
  app/components-react/editor/elements/RecentEvents.tsx
  app/services/recent-events.ts
Labels: bug, bundle release
