Repository streamlabs/desktop, pull requests merged in 2023-07, with the labels that each got.

#4607 Add Announcement Banner
  app/components-react/root/Banner.m.less
  app/components-react/root/Banner.tsx
  app/components-react/shared/TitleBar.tsx
  app/services/announcements.ts
Labels: enhancement

#4613 Fix api and style issues for banner
  app/components-react/root/Banner.m.less
  app/components-react/root/Banner.tsx
  app/services/announcements.ts
  test/regular/widgets/alertbox.ts
Labels: current bundle

#4615 Prevent Banner showing up in Child Window
  app/components-react/shared/TitleBar.tsx
  app/services/announcements.ts
Labels: bug, current bundle

#4589 Migrate GLVolmeters to React
  app/components-react/index.ts
  app/components-react/root/GLVolmeters.tsx
  app/components/editor/elements/Mixer.tsx
  app/components/shared/ReactComponentList.tsx
Labels: react

#4620 Fix css jank in the top banner
  app/components-react/root/Banner.m.less
Labels: bug

#4634 Hide Tweet feature until fixed
  app/components-react/windows/go-live/GoLiveSettings.tsx
Labels: bug

#4636 Hide extras section if no viable actions
  app/components-react/windows/go-live/GoLiveSettings.tsx
Labels: bug
