Repository streamlabs/desktop, pull requests merged in 2024-06, with the labels that each got.

#4881 fix(build): react-devtools build folder was ignored
  main.js
  vendor/react-devtools/build/background.js
  vendor/react-devtools/build/importFile.worker.worker.js
  vendor/react-devtools/build/installHook.js
  vendor/react-devtools/build/main.js
  vendor/react-devtools/build/panel.js
  vendor/react-devtools/build/parseHookNames.chunk.js
  vendor/react-devtools/build/parseSourceAndMetadata.worker.worker.js
  vendor/react-devtools/build/prepareInjection.js
  vendor/react-devtools/build/proxy.js
  vendor/react-devtools/build/react_devtools_backend.js
  vendor/react-devtools/build/renderer.js
  vendor/react-devtools/build/vendors~parseHookNames.chunk.js
Labels: on hold

#5024 Fix missing play alert button
  app/components-react/widgets/AlertBox.tsx
Labels: bug

#5040 Update authentication for open with
  app/components-react/highlighter/StorageUpload.tsx
  app/components-react/pages/RecordingHistory.tsx
  app/components-react/windows/settings/Stream.tsx
  app/services/user/index.ts
Labels: enhancement

#5042 Move max char limit to tooltip
  app/components-react/windows/go-live/CommonPlatformFields.tsx
  app/i18n/en-US/tiktok.json
Labels: enhancement

#5044 Fix swapped links for login and signup
  app/components-react/highlighter/StorageUpload.tsx
Labels: current bundle, P0

#5045 Fix non-platform logins
  app/components-react/highlighter/StorageUpload.tsx
  app/components-react/pages/onboarding/Connect.tsx
  app/components-react/pages/onboarding/ExtraPlatformConnect.tsx
  app/components-react/pages/onboarding/PrimaryPlatformSelect.tsx
  app/services/user/index.ts
Labels: current bundle

#5043 refactor(test): ensure user is released from pool on failures
  test/helpers/webdriver/user.ts
  test/regular/api/streaming.ts
  test/regular/streaming/dual-output.ts
  test/regular/streaming/instagram.ts
  test/regular/streaming/multistream.ts
  test/regular/streaming/tiktok.ts
  test/regular/streaming/twitter.ts
Labels: P0
