Repository streamlabs/desktop, pull requests merged in 2024-10, with the labels that each got.

#5142 Remove deprecated files
  app/components/custom-source-properties/WidgetProperties.vue
  app/components/custom-source-properties/WidgetProperties.vue.ts
  app/components/windows/SourceProperties.vue.ts
  app/components/windows/settings/HotkeyGroup.tsx
  app/components/windows/settings/Hotkeys.vue
  app/components/windows/settings/Hotkeys.vue.ts
Labels: tech debt

#5146 An get rid of useModule in StudioFooter
  app/components-react/root/StudioFooter.tsx
Labels: tech debt

#5166 Remove reference to deprecated thumbnail editor
  app/components-react/windows/go-live/platforms/YoutubeEditStreamInfo.tsx
  app/i18n/en-US/youtube.json
Labels: enhancement

#5172 Fix go live checklist icon colors.
  app/components-react/windows/go-live/GoLiveChecklist.m.less
Labels: needs QA

#5171 Fix streamlabels line break.
  app/components-react/windows/SourceProperties.tsx
  app/services/sources/sources.ts
  app/services/streamlabels/index.ts
Labels: needs QA

#5087 Update Remote Control API
  app/app-services.ts
  app/components-react/windows/settings/RemoteControl.m.less
  app/components-react/windows/settings/RemoteControl.tsx
  app/i18n/en-US/remote-control.json
  app/services/api/remote-control-api.ts
  app/services/api/tcp-server/tcp-server.ts
Labels: ready for review

#5182 Add section to RemoteControl for third party use
  app/components-react/windows/settings/RemoteControl.m.less
  app/components-react/windows/settings/RemoteControl.tsx
  app/i18n/en-US/remote-control.json
  app/services/api/tcp-server/tcp-server.ts
Labels: bug

#5190 Error handling for source creation failure.
  app/services/scene-collections/nodes/sources.ts
  app/services/scene-collections/scene-collections.ts
  app/services/sources/sources.ts
Labels: needs QA

#5192 Fix strictnulls and other tests.
  app/services/scene-collections/scene-collections.ts
Labels: work in progress, needs QA

#5195 Fix socket reconnect logic
  app/services/api/remote-control-api.ts
Labels: bug, P0
