Repository streamlabs/desktop, pull requests merged in 2024-05, with the labels that each got.

#4992 Fix Dual Output Diagnostic Upload
  app/services/diagnostics.ts
Labels: bug

#4984 Revert "Revert "Dual Output collection: refactor create, optimize load, repair on load.""
  app/components-react/editor/elements/SceneSelector.tsx
  app/components-react/root/StudioEditor.tsx
  app/components-react/windows/go-live/dual-output/UltraDestinationSwitchers.tsx
  app/i18n/en-US/app.json
  app/services/dual-output/dual-output.ts
  app/services/scene-collections/nodes/scene-items.ts
  app/services/scene-collections/scene-collections.ts
  app/services/scenes/scene-item.ts
  app/services/scenes/scene.ts
  app/services/scenes/scenes.ts
  test/data/scene-collections/single-output-collection/single-output-collection-manifest.json
  test/data/scene-collections/single-output-collection/single-output-collection.json
  test/regular/api/scenes.ts
  test/regular/services/scene-collections/scene-collections.ts
  test/regular/streaming/dual-output.ts
  test/regular/streaming/multistream.ts
Labels: ready for review

#4998 Hide game field for Facebook
  app/components-react/windows/go-live/platforms/FacebookEditStreamInfo.tsx
  app/i18n/en-US/settings.json
  app/i18n/en-US/twitch.json
  app/services/platforms/facebook.ts
  test/regular/streaming/facebook.ts
Labels: bug, P0

#5001 Revert PerformanceService from Realm
  app/components-react/pages/ThemeAudit.tsx
  app/components-react/root/StudioFooter.tsx
  app/components-react/shared/PerformanceMetrics.tsx
  app/components-react/windows/AdvancedStatistics.tsx
  app/services/performance.ts
  app/services/touch-bar.ts
Labels: bug, current bundle

#5000 osn update with a fix for mac os screen capture renamed
  scripts/repositories.json
Labels: bug, P0

#4994 Renamed screen_capture to mac_screen_capture type for macOS
  app/services/sources/sources-api.ts
  app/services/sources/sources-data.ts
  app/services/sources/sources.ts
Labels: bug, P0

#5003 Another attempt at fixing flaky hotkey test.
  test/regular/highlighter.ts
  test/regular/settings/hotkeys.ts
Labels: tech debt

#4993 Fix adding Streamlabs Multistream as a custom destination
  app/components-react/shared/inputs/FormFactory.tsx
  app/components-react/shared/inputs/metadata.ts
  app/components-react/windows/settings/Stream.tsx
  app/i18n/en-US/settings.json
Labels: P0

#5006 Fix resizing items on vertical displays
  app/components-react/shared/Display.tsx
  app/services/editor.ts
Labels: bug, ready for review
