Repository streamlabs/desktop, pull requests merged in 2024-01, with the labels that each got.

#4797 Update osn to v0.24
  scripts/repositories.json
Labels: draft

#4832 Fix Advanced Overlay Transitions
  app/services/platform-apps/platform-app-assets-service.ts
Labels: bug

#4833 Add username to logout confirmation
  app/components-react/sidebar/NavTools.tsx
  app/components/windows/settings/Settings.vue.ts
  app/i18n/en-US/common.json
Labels: enhancement

#4838 Fix bar2 responsiveness and initializing new layouts
  app/components-react/editor/layouts/Default.tsx
  app/components-react/editor/layouts/FourByFour.tsx
  app/components-react/editor/layouts/Triplets.tsx
  app/components-react/editor/layouts/TwoPane.tsx
  app/components-react/editor/layouts/hooks.tsx
  app/components-react/root/ResizeBar.tsx
Labels: bug

#4840 Fix TransformScale on FourByFour Layout
  app/components-react/editor/layouts/FourByFour.tsx
Labels: bug, current bundle

#4843 Facebook: Handle 403 response errors when fetching scheduled streams
  app/services/platforms/facebook.ts
Labels: bug

#4852 Move FB API to v16
  app/services/platforms/facebook.ts
Labels: bug, enhancement
