Repository streamlabs/desktop, pull requests merged in 2024-08, with the labels that each got.

#5084 Fix typo and conditional logic for apply prompt.
  app/components-react/shared/InfoBanner.tsx
  app/components-react/windows/go-live/platforms/TiktokEditStreamInfo.tsx
  app/i18n/en-US/tiktok.json
  app/services/platforms/tiktok.ts
  app/services/platforms/tiktok/api.ts
  test/regular/streaming/tiktok.ts
Labels: P0

#5085 Add TikTok replay noty.
  app/i18n/en-US/tiktok.json
  app/services/platforms/tiktok.ts
Labels: P0

#5088 Update Support Link
  app/app-services.ts
  app/components-react/sidebar/NavTools.tsx
  app/components-react/windows/settings/Support.tsx
  app/services/hosts.ts
Labels: enhancement

#5095 Add mp4 support to media gallery
  app/components-react/windows/MediaGallery.tsx
  app/services/media-gallery/media-gallery.ts
Labels: bug

#5098 Filter out preview alerts from mini feed (recent events)
  app/services/recent-events.ts
Labels: bug

#5091 Platform link update
  app/components-react/pages/BrowseOverlays.tsx
  app/components-react/pages/PlatformAppStore.tsx
  app/services/user/index.ts
Labels: on hold

#5100 Fix preview thumbnail
  app/components-react/shared/inputs/MediaUrlInput.tsx
  app/components/shared/inputs/MediaGalleryInput.vue
Labels: bug, current bundle

#5109 Fix useRealmObject updating every tick
  app/components-react/hooks/realm.ts
Labels: bug, P0
