Repository streamlabs/desktop, pull requests merged in 2025-07, with the labels that each got.

#5496 Fixes for flaky tests.
  test/data/dummy-accounts.ts
  test/regular/streaming/multistream.ts
  test/regular/streaming/tiktok.ts
  test/regular/streaming/twitter.ts
Labels: tech debt

#5506 Only display audio notifications if live or recording
  app/components-react/root/StudioEditor.tsx
Labels: enhancement

#5507 Fix instagram title not updating correctly
  app/services/platforms/instagram.ts
Labels: bug
