Repository streamlabs/desktop, pull requests merged in 2025-02, with the labels that each got.

#5293 Add YT stream ids to analytics
  app/services/streaming/streaming.ts
Labels: analytics

#5294 Revert "[hotfix] highlighter - fix remove need of stream id"
  app/components-react/highlighter/PreviewModal.tsx
Labels: current bundle

#5296 Embed TikTok chat.
  app/components-react/root/LiveDock.tsx
  app/services/platforms/tiktok.ts
  app/services/platforms/tiktok/api.ts
Labels: needs QA

#5300 Fix kick buttons with new icon
  app/styles/buttons.less
Labels: bug

#5302 Fix kick icon while hovering
  app/themes.g.less
Labels: bug

#5306 Add analytics to scheduled streams
  app/components-react/pages/stream-scheduler/useStreamScheduler.tsx
  app/services/platforms/facebook.ts
  app/services/platforms/youtube.ts
  app/services/usage-statistics.ts
Labels: analytics

#5309 Fix HighlightGenerator form translations
  app/components-react/highlighter/HighlightGenerator.tsx
  app/i18n/en-US/highlighter.json
Labels: bug
