Repository streamlabs/desktop, pull requests merged in 2025-04, with the labels that each got.

#5336 Add Advanced Recording test.
  app/components-react/pages/RecordingHistory.tsx
  app/i18n/en-US/streaming.json
  app/services/settings/output/output-settings.ts
  app/services/streaming/streaming.ts
  test/helpers/modules/settings/settings.ts
  test/regular/recording.ts
  test/regular/replay-buffer.ts
Labels: ready for review

#5363 Fix duplicated options in video settings
  app/components-react/windows/settings/Video.tsx
Labels: bug

#5373 Fix vertical resolutions reverting to default
  app/services/auto-config/index.ts
  app/services/video.ts
Labels: bug, P0

#5374 Fix Stale FPS Values
  app/components-react/windows/settings/Video.tsx
  app/services/performance.ts
  app/services/settings/output/output-settings.ts
  app/services/ts-importer.ts
  app/services/video.ts
Labels: bug, P0
