Repository streamlabs/desktop, pull requests merged in 2025-08, with the labels that each got.

#5517 Add toggle to disable muted notifications
  app/components-react/root/StudioEditor.tsx
  app/components-react/windows/advanced-audio/GlobalSettings.tsx
  app/i18n/en-US/audio.json
  app/services/hardware/default-hardware.ts
Labels: enhancement

#5451 Merge stream avatar working branch into staging
  app/app-services.ts
  app/components-react/sidebar/AppsNav.tsx
  app/services/app/app.ts
  app/services/platform-apps/api/index.ts
  app/services/platform-apps/api/modules/module.ts
  app/services/platform-apps/api/modules/native-components.ts
  app/services/platform-apps/api/modules/sources.ts
  app/services/platform-apps/api/modules/streaming-recording.ts
  app/services/platform-apps/api/modules/twitch.ts
  app/services/platform-apps/container-manager.ts
  app/services/platform-apps/index.ts
  app/services/platforms/twitch.ts
  app/services/platforms/twitch/api.ts
  app/services/stream-avatar/avatar-updater.ts
  app/services/stream-avatar/stream-avatar-service.ts
  app/services/stream-avatar/vision-updater.ts
  guest-api/index.ts
  package.json
  yarn.lock
Labels: blocked

#4853 Port Main Window to React
  app/app.ts
  app/components-react/editor/elements/LegacyEvents.tsx
  app/components-react/editor/elements/Mixer.tsx
  app/components-react/editor/elements/index.ts
  app/components-react/editor/elements/mixer/GLVolmeters.tsx
  app/components-react/editor/layouts/Classic.tsx
  app/components-react/editor/layouts/Default.tsx
  app/components-react/editor/layouts/FourByFour.tsx
  app/components-react/editor/layouts/OnePane.tsx
  app/components-react/editor/layouts/OnePaneR.tsx
  app/components-react/editor/layouts/Pyramid.tsx
  app/components-react/editor/layouts/Triplets.tsx
  app/components-react/editor/layouts/TwoPane.tsx
  app/components-react/editor/layouts/hooks.tsx
  app/components-react/index.ts
  app/components-react/pages/AlertboxLibrary.tsx
  app/components-react/pages/BrowseOverlays.tsx
  app/components-react/pages/Loader.tsx
  app/components-react/pages/PatchNotes.tsx
  app/components-react/pages/PlatformAppMainPage.tsx
  app/components-react/pages/PlatformAppStore.tsx
  app/components-react/pages/PlatformMerge.tsx
  app/components-react/pages/RecordingHistory.tsx
  app/components-react/pages/Studio.tsx
  app/components-react/pages/ThemeAudit.tsx
  app/components-react/pages/index.ts
  app/components-react/root/LiveDock.m.less
  app/components-react/root/LiveDock.tsx
  app/components-react/root/ReactRoot.tsx
  app/components-react/root/ResizeBar.m.less
  app/components-react/root/ResizeBar.tsx
  app/components-react/shared/TitleBar.tsx
  app/components-react/shared/modals/MessageBoxModal.m.less
  app/components-react/shared/modals/MessageBoxModal.tsx
  app/components-react/shared/modals/Modal.m.less
  app/components-react/shared/modals/Modal.tsx
  app/components-react/shared/modals/ModalWrapper.tsx
  app/components-react/windows/Main.m.less
  app/components-react/windows/Main.tsx
  app/components-react/windows/sharedComponentsLibrary/SharedComponentsLibrary.tsx
  app/components/shared/ReactComponentList.tsx
  app/components/windows/Main.tsx
  app/components/windows/Main.vue
  app/components/windows/Main.vue.ts
  app/services/customization.ts
  app/services/layout/index.ts
  app/services/layout/layout-data.ts
  app/services/windows.ts
  test/helpers/modules/core.ts
  test/helpers/modules/onboarding.ts
  test/helpers/webdriver/index.ts
  test/regular/startup.ts
Labels: ready for review, react

#5434 Refactor display rendering to handle its own style blocking
  app/components-react/editor/elements/RecordingPreview.tsx
  app/components-react/editor/elements/StreamPreview.tsx
  app/components-react/root/StudioEditor.tsx
  app/components-react/shared/Display.tsx
  app/components-react/windows/Projector.tsx
  app/components-react/windows/SourceProperties.tsx
  app/components/windows/SourceProperties.vue
  app/components/windows/SourceProperties.vue.ts
  app/components/windows/WidgetEditor.vue
  app/components/windows/WidgetEditor.vue.ts
Labels: on hold, tech debt

#5534 Make chat resize smoother
  app/components-react/root/ResizeBar.tsx
  app/components-react/windows/Main.m.less
  app/components-react/windows/Main.tsx
Labels: bug, current bundle

#5536 [Mac crash fix] do not resize with 0 width/height
  app/services/video.ts
Labels: bug

#5532 Add method to support A/B testing
  app/services/user/index.ts
Labels: enhancement

#5535 Add scene collection load time log.
  app/services/app/app.ts
Labels: enhancement
